### ISSUE TITLE
ally.sh, e-glossa.it, italiashare.life Anti Adblock

### ISSUE THREAD

**Issue by bup4gr** [uBlockOrigin/uAssets#1144]
### URL(s) where the issue occurs
http://ally.sh/KJnIe
https://www.e-glossa.it
http://www.italiashare.life

### Describe the issue
1) ally
![1](https://user-images.githubusercontent.com/27068733/34454813-0e306b5a-ed6b-11e7-95c6-6a601d2c8681.jpg)
2) e-glossa
![2](https://user-images.githubusercontent.com/27068733/34454816-21c8fba0-ed6b-11e7-92b4-5f06d6663d43.jpg)

3) italiashare filter don't work

Ublock 1.14.22 with last firefox ESR

**Comment by mapx-** [comment]
ally.sh:
`@@||pagead2.googlesyndication.com/pagead/$script,domain=ally.sh`

**Comment by bup4gr** [comment]
The filters for `ally.sh` and `e-glossa.it` works.
But is possible to made a filter that don't allow `googlesyndication.com`, maybe with `##script:inject`?
I have this rule `* googlesyndication.com * block` and i don't want to disable it.

For `italiashare.life` the fix don't work. There is always a redir to this page `http://www.italiashare.life/adblock/index.html` (how to disable adblock).
Previous fixes are https://github.com/uBlockOrigin/uAssets/issues/440 and https://github.com/uBlockOrigin/uAssets/issues/693.

**Comment by mapx-** [comment]
I get no anti adb for italiashare (when I go on the various articles) using the filter above.
Do you have some specific page where you get redirect ? Be sure you have no other `rule` for the site

For the other 2 sites I tried redirect filters, don't work

**Comment by mapx-** [comment]
for e-glossa seems working:

`e-glossa.it##script:inject(abort-on-property-read.js, VerificaAdBlockers)`

**Comment by okiehsch** [comment]
- `ally.sh` I can't see a `script:inject-fix` that does not also break the site.

- `e-glossa.it`  `e-glossa.it##script:inject(setTimeout-defuser.js, Blocco, 2000)` works for me.

- `italiashare.life` can't reproduce, same as mapx-.

**Comment by okiehsch** [comment]
`e-glossa.it##script:inject(abort-on-property-read.js, VerificaAdBlockers)`
breaks parts of `https://www.e-glossa.it/ScriptResource.axd` as I get some jQuery errors, I can't
read italian, so you are better equipped to see if this breaks any important site functionality :).

**Comment by mapx-** [comment]
I didn't see anomalies, but I don't visit the site ..so I added your filter (no errors in browser console)

**Comment by ghajini** [comment]
Add bypassing logic?

**Comment by bup4gr** [comment]
Thanks for your fixes.

Today i try to investigate my `italiashare.life` problem, but the site is completly changed.
Try `http://www.italiashare.life/e-books/libreria-dasolo-download/narrativa-e-letteratura/666252-george-orwell-1984-1989.html`

Now this filters works for me:
```
@@||www.italiashare.life/uploads/adframe.js$script,domain=www.italiashare.life
www.italiashare.life##.admitad-checker-popup-bg
www.italiashare.life##.admitad-checker-popup-body
www.italiashare.life##.admitad-checker-popup-header
www.italiashare.life###admitad-cookie-check-popup
```

I'not so expert to use `script:inject` instead of allow `www.italiashare.life/uploads/adframe.js`

Another things: `italiashare.life` block the mouse right click (appear a message "this is function disabled).
Is there a way to allow the mouse right click? Is possible with `script:inject`?

**Comment by okiehsch** [comment]
I can't see any problem at `http://www.italiashare.life/e-books/libreria-dasolo-download/narrativa-e-letteratura/666252-george-orwell-1984-1989.html` on my end.

The only issue I can reproduce is the "blocks mouse right click" one.
This is fixed with `italiashare.life##script:inject(abort-on-property-write.js, killCopy)`
which I will add to **`uBlock-annoyances`**.

**Comment by marmooz** [comment]
it seems that the problems is not solved :(
example : http://ally.sh/NC5Gx

**Comment by KiLL4FuNK** [comment]
Page is loading
Please wait...

`https://al.ly/CIxQvH`
