### ISSUE TITLE
poedb.tw: detection

### ISSUE THREAD

**Issue by TheHonzai** [uBlockOrigin/uAssets#11977]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://poedb.tw/us/`

### Category

detection

### Describe the issue

With uBO activated I get nothing displayed, but it works with uBO disabled. Asked a friend and they were having similar results.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.41.8
Firefox: 97
filterset (summary): 
  network: 79794
  cosmetic: 41373
  scriptlet: 16455
  html: 624
listset (total-discarded, last updated): 
  default: 
    user-filters: 3-0, never
    ublock-filters: 30861-27, 27m
    ublock-badware: 3903-3, 27m
    ublock-privacy: 208-0, 27m
    ublock-abuse: 72-0, 27m
    ublock-unbreak: 1731-0, 27m
    easylist: 64097-615, 27m
    easyprivacy: 26634-571, 27m
    urlhaus-1: 8437-0, 27m
    plowe-0: 3673-2, 27m
filterset (user): [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 562 ms (selfie)
  maxAssetCacheWait: 133 ms
popupPanel: 
  blocked: 4
  blockedDetails: 
    google-analytics.com: 1
    googlesyndication.com: 1
    nitropay.com: 2
```
</details>

**Comment by okiehsch** [comment]
Fixed with
https://github.com/uBlockOrigin/uAssets/commit/2701f6c7efba21b056a38da2d33b77edcf363170

**Comment by MatthewClair** [comment]
This page is still broken in Firefox.  The same settings work in Chrome.  The console has this error:

```
Uncaught TypeError: cannot declare global binding 'adBlockDetected': property must be configurable or both writable and enumerable
    <anonymous> https://poedb.tw/us/:533
```

**Comment by Procyon-b** [comment]
@MatthewClair It works for me in both browsers (with similar error in the console).
In the "_Filter Lists_" tab, "_Purge all caches_" and "_Update now_".

**Comment by MatthewClair** [comment]
Yeah it appears to be working now.
