### ISSUE TITLE
Kissasian.ch has active anti-adblock

### ISSUE THREAD

**Issue by MarsWanKenobi** [uBlockOrigin/uAssets#1370]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[http://kissasian.ch/Drama/Age-of-Youth-2/Episode-1?id=34574&s=beta&pfail=1`]

### Describe the issue

When navigating to above link or any video on that URL, video plays for a bit then throws up a "disable adblock to continue" error preventing videos from playing.

### Screenshot(s)

http://prntscr.com/i5exwb

### Versions

- Browser/version: [Firefox Nightly 60.0a1 01-25-2018]
- uBlock Origin version: [1.14.24]

### Settings

- None - default lists used,

**Comment by MarsWanKenobi** [comment]
Gorhill mentioned that Tracking Protection might been a possible cause in the previous thread about this site but I do not have that enabled. I mentioned a new profile worked last time but it does not this time. I am on Sierra 10.12.6.

**Comment by gorhill** [comment]
> video plays for a bit then

How long is "for a bit"? It helps to have a ballpark figure to know how much I have to wait in trying to reproduce.

**Comment by gorhill** [comment]
Unable to reproduce with FF58, I waited 2 minutes.

Something else on your side could prevent uBO's filters to take effects. Can be Tracking Protection, hosts files in your OS, custom browser settings, other extensions interfering, etc. You will have to investigate on your side.

**Comment by gorhill** [comment]
Actually I can reproduce on Nightly. Investigating.

**Comment by gorhill** [comment]
This is worrisome. I am seeing the following warning in the browser console:

> Redirecting to insecure data: URI not allowed (Blocked loading of: “data:application/javascript;base64,KGZ1bmN0aW9uKCk...”)

This does not happens with FF58. So this the most likely explanation, Nightly now forbids to redirect blocked network requests to data: URIs.

**Comment by gorhill** [comment]
Looks like this is what breaks uBO's ability to redirect to neutering local scripts:
<https://bugzilla.mozilla.org/show_bug.cgi?id=1428793>

**Comment by MarsWanKenobi** [comment]
From what I'm reading, seems like Mozilla needs to fix it on their end. Looks like the patch above is riding the trains to 60 so I'll need to fall back to 58 until this gets sorted. Do you have any alternative ways to get rid of this or is that bridge burned on Nightly?

**Comment by gorhill** [comment]
Yes, it's a browser bug, I reported the issue to them, it seems their test as to whether the data: URI should be blocked is overzealous -- the fix does more than what it was supposed to address. I am optimistic this will be fixed quickly, meanwhile follow the issue on bugzilla to inquire about progress.

**Comment by uBlock-user** [comment]
They fixed in FF 60, so you will have wait for a while or switch to 60.

**Comment by MarsWanKenobi** [comment]
@uBlock-user, running the latest Nightly 60 build and the issue with uBO not redirecting to local scripts still persists on the site in question. I have to go back to 58 to get it working properly. So far I haven't noticed any other sites with this behavior.

**Comment by uBlock-user** [comment]
@MarsWanKenobi the bug listed by gorhill is patched in 60 however this broke neutered scripts in uBO according to this one - https://bugzilla.mozilla.org/show_bug.cgi?id=1434357
