### ISSUE TITLE
aliexpress.com: breakage

### ISSUE THREAD

**Issue by sendit2ash** [uBlockOrigin/uAssets#15629]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.aliexpress.com/premium/4mm-hex-shank.html?trafficChannel=ppc&d=y&CatId=0&SearchText=4mm+hex+shank&ltype=premium&SortType=default&page=3`

### Category

breakage

### Describe the issue

When searching on aliexpress, the EasyList filter is blocking the results.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![2022-11-11 23_38_31-uBlock₀ — Logger](https://user-images.githubusercontent.com/44042999/201343149-c10ad899-c268-45b1-b3fd-a0770e38218b.png)

![2022-11-11 23_38_10-uBlock₀ — Logger](https://user-images.githubusercontent.com/44042999/201343153-47d2a385-02b6-462b-8d74-530ea16d9560.png)

![2022-11-11 23_39_03-uBlock₀ — Asset viewer and 39 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/44042999/201343166-5bc75990-b876-4dc2-8281-80169a614d7b.png)

![2022-11-11 23_40_48-4mm hex shank - Buy 4mm hex shank with free shipping on AliExpress - page 3 - Pe](https://user-images.githubusercontent.com/44042999/201343155-177303c1-2739-433c-b0f5-edf475788319.png)

![2022-11-11 23_40_40-4mm hex shank - Buy 4mm hex shank with free shipping on AliExpress - page 3 and ](https://user-images.githubusercontent.com/44042999/201343163-732b9ad8-dcf0-41c1-8868-76e1426915b6.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.0
Chromium: 107
filterset (summary): 
  network: 90481
  cosmetic: 38519
  scriptlet: 16682
  html: 0
listset (total-discarded, last-updated): 
  default: 
    user-filters: 24-0, never
    easylist: 64356-52, 4d.5h.17m
    easyprivacy: 30779-1171, 4d.5h.16m
    plowe-0: 3669-867, 10d.10h.16m
    ublock-abuse: 76-0, 1d.45m
    ublock-badware: 3968-109, 1d.4h.54m
    ublock-filters: 31166-106, 1d.4h.53m
    ublock-privacy: 257-1, 1d.44m
    ublock-quick-fixes: 538-10, 2h.14m
    ublock-unbreak: 1893-42, 1d.4h.56m
    urlhaus-1: 11473-0, 2h.15m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 3 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 150 ms (selfie)
  maxAssetCacheWait: 111 ms
popupPanel: 
  blocked: 29
  blockedDetails: 
    alicdn.com: 2
    criteo.net: 2
    facebook.net: 1
    go-mpulse.net: 2
    google-analytics.com: 1
    googletagmanager.com: 1
    mmstat.com: 20
```
</details>

**Comment by mapx-** [comment]
- Update all filter lists
- Are you using the last dev build of uBO for chrome ? try updating it again

**Comment by gorhill** [comment]
Maybe related to <https://github.com/uBlockOrigin/uBlock-issues/issues/2356>, fixed in 1.45.1b0.

**Comment by sendit2ash** [comment]
I've forced updated all of the filters, didn't fix it.
I installed the latest version 1.45.2 and also tried 1.45.1b1 and both have the same issue.
Disabling uBO fixes the issue.
It also works if I browse in incognito. 
Interestingly incognito also returns different results.

Looking at the links for the search results, the following URL is provided in incognito:
```
https://www.aliexpress.com/item/1005004883902767.html?spm=a2g0o.productlist.0.0.76905f034S42JY
&algo_pvid=a42cf6fd-340b-403d-92d1-d89980c0ab1e
&algo_exp_id=a42cf6fd-340b-403d-92d1-d89980c0ab1e-0
&pdp_ext_f=%7B%22sku_id%22%3A%2212000030883272242%22%7D
&pdp_npi=2%40dis%21AUD%212.08%211.42%21%21%21%21%21%40210318c216681786846027604e4414%2112000030883272242%21sea
&curPageLogUid=mL1O7glXrP18
```

And this is what is a normal link for a search result:
```
https://www.aliexpress.com/item/1005004873281901.html?spm=a2g0o.productlist.0.0.7ec05f03kWNmZw
&algo_pvid=f062c14e-dabc-43b6-971f-93c0a9cee94a
&aem_p4p_detail=202211110709027239422317530240013980724
&algo_exp_id=f062c14e-dabc-43b6-971f-93c0a9cee94a-0
&pdp_ext_f=%7B%22sku_id%22%3A%2212000030840426564%22%7D
&pdp_npi=2%40dis%21AUD%219.32%215.5%21%21%21%21%21%402101fd4b16681793423904481e3bf2%2112000030840426564%21sea
&curPageLogUid=zOuOnIGjCdyo
&ad_pvid=202211110709027239422317530240013980724_1
```

The part of the URL that is being picked up by EasyList is "&aem_p4p_detail="
I don't know why this generates as part of the links when browsing normally, even after I have cleared all browser cache and have cache disabled through DevTools

**Comment by gorhill** [comment]
> I installed the latest version 1.45.2 and also tried 1.45.1b1 and both have the same issue

Did you force an update of the filter lists? This needs to be done to force filters to be recompiled.

**Comment by stephenhawk8054** [comment]
I see that OP's original link has `/premium/` on it, while in incognito or when not logged in, it converts to `/item/`. I guess it needs an account to log in to reproduce?

**Comment by sendit2ash** [comment]
I've force updated all of the filters after installing the newer versions, didn't fix it.

@stephenhawk8054 Hadn't noticed that but yes, the URL has /premium/ in it.

I am not logged in on the website, but when I search (not logged in) the URL that it takes me to is:
https://www.aliexpress.com/premium/4mm-hex-shank.html?d=y&origin=y&catId=0&initiative_id=SB_20221111192650&SearchText=4mm%20hex%20shank&spm=a2g0o.cart.1000002.0

If I search in incognito the URL it takes me to is:
https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20221111192429&SearchText=4mm+hex+shank&spm=a2g0o.tm800082350.1000002.0

**Comment by stephenhawk8054** [comment]
Yeah, I don't know how to reproduce the `/premium/` link. It automatically takes me to `wholesale` one, but that page loads normally without results being blocked.

**Comment by mapx-** [comment]
```
What is AliExpress premium?
Packages that are sent with AliExpress Standard Shipping usually take 15 to 45 working days, whereas Aliexpress Premium Shipping will provide an estimated delivery time from 7 to 15 working days.
```

**Comment by mapx-** [comment]
@sendit2ash did you try clearing all cookies / storage for AliExpress ?

**Comment by sendit2ash** [comment]
@mapx- I have, and it works as long as I don't log in. Once I log in (e.g. to place an order) my shopping cart is saved to cache and the issue repeats from then on. 
I don't want to have to clear my cache/storage for Aliexpress every time I access it as I have to go through 2FA every time

**Comment by mapx-** [comment]
ok, so your account is a premium one, to investigate we need your credentials => let me know if you want to send me them, if not it's nothing we can do about

**Comment by sendit2ash** [comment]
I don't have a "premium" account, as far as I'm aware there's no way to get a premium account.

I'm not willing to share my account credentials.

I have identified the issue is coming from EasyList, specifically the following setting within the filter:
`aliexpress.com##a[href*="aliexpress.com/item/"][href*="&aem_p4p_detail="]`

Can you not verify the validity of this specific setting?

Is there a way that I can ignore this setting for Aliexpress but continue to use EasyList?

**Comment by mapx-** [comment]
add

`aliexpress.com#@#a[href*="aliexpress.com/item/"][href*="&aem_p4p_detail="]`

**Comment by sendit2ash** [comment]
@mapx- Do I add that to my filter list? Because I have added it and it has no effect

**Comment by sendit2ash** [comment]
Nevermind, found there as a second issue blocking.
Added the following as well fixed the issue:
`aliexpress.com#@#a:has(> div img + span:has-text(/AD|Ann.|Annonce|Anuncio|Anúncio|Anzeige|Reklama|Reklam|מודעה|광고|إعلان/))`

**Comment by stephenhawk8054** [comment]
@sendit2ash Do you have a link of any product that has Aliexpress Premium shipping on your side?

**Comment by sendit2ash** [comment]
@stephenhawk8054 I don't sorry. I cleared my cart while I was testing and I don't have any active purchases. 
I'm also not sure how to actually apply "Premium shipping" as none of the products I have seen so far have the option
