### ISSUE TITLE
bluecinema.ch: breakage

### ISSUE THREAD

**Issue by Toeoe6204** [uBlockOrigin/uAssets#15647]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

https://bluecinema.ch/de/wm-de/

### Category

breakage

### Describe the issue

At the end of the page there should be a list of buttons for different locations. But they are not visible whit uBO active.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![grafik](https://user-images.githubusercontent.com/71825200/201496870-ef483fc4-1647-4663-880f-24f116dc7cb9.png)

</details>

### Configuration

breakage

**Comment by Toeoe6204** [comment]
Does still not work.

**Comment by mapx-** [comment]
add all the requested info in the template (configuration = breakage !?):

- go to support tab
- copy here `Troubleshooting Information`

**Comment by mapx-** [comment]
I guiess you are using fanboy's annoyances list, in this case add:

```
@@||loader.wisepops.com/get-loader.js$script,domain=bluecinema.ch
@@||popup.wisepops.com/my-wisepop$xhr,domain=bluecinema.ch
@@||cdn.wisepops.com/shared/wisepops/$script,domain=bluecinema.ch
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by Toeoe6204** [comment]
> I guess you are using `fanboy's annoyances` list (or `AdGuard annoyances` one), in this case add:
> 
> ```
> @@||loader.wisepops.com/get-loader.js$script,domain=bluecinema.ch
> @@||popup.wisepops.com/my-wisepop$xhr,domain=bluecinema.ch
> @@||cdn.wisepops.com/shared/wisepops/$script,domain=bluecinema.ch
> ```

No, I don't use them.

**Comment by Toeoe6204** [comment]
> add all the requested info in the template (configuration = breakage !?):
> 
>     * go to support tab
> 
>     * copy here `Troubleshooting Information`
> 
>     * update all filter lists
> 
>     * disable any other blocking extension / addon

done
Thank you for your help.

**Comment by mapx-** [comment]
@Toeoe6204 if still does not work for you, update uBO for firefox to the last build (and then you have to update again all your filter lists)

https://github.com/gorhill/uBlock/releases/tag/1.45.3b0

(Firefox: Click ...)

**Comment by Toeoe6204** [comment]
It works now, thank you very much!
