### ISSUE TITLE
soranews24.com: detection

### ISSUE THREAD

**Issue by krisu5** [uBlockOrigin/uAssets#15705]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625)
- [X] I verified the issue is not caused by the browser built-in blocker, or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through VPN)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://soranews24.com/2022/11/18/tokyos-moomin-cafes-are-closing-soon-but-our-reporter-had-an-experience-shell-never-forget/`

### Category

detection

### Describe the issue

SoraNews24 detects uBlock Origin, blocks images from displaying from article and replaces the article images instead with `span.adb-wrap` elements that has text: *Please allow ads on our site: If ads are blocked, images will not be displayed and other functions will be limited. SoraNews24 strives to ensure that ads do not interfere with the reading of articles. We appreciate your contribution to our operating fund.*

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Screenshot 2022-11-18 at 15-04-57 Tokyo’s Moomin Cafes are closing soon but our reporter had an experience she’ll never forget](https://user-images.githubusercontent.com/3540275/202711887-af7884f0-fa67-4d13-aef1-1b6090722a2a.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.45.3b4
Firefox: 106
filterset (summary): 
  network: 281130
  cosmetic: 76053
  scriptlet: 48953
  html: 901
listset (total-discarded, last-updated): 
  added: 
    https://easylist-msie.adblockplus.org/antiadblockfilters.txt: 0-0, 16h.40m
    https://paulgb.github.io/BarbBlock/blacklists/ublock-origin.txt: 550-6, 4d.17h
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2005-1, 16h.39m
    https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 24201-72, 12h.37m
    https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt: 1062-0, 2d.14h.51m
    https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/google_duckduckgo/global.txt: 4641-0, 16h.38m
    adguard-generic: 65684-5195, 1d.11h.11m
    curben-phishing: 163616-10, 16h.43m
    curben-pup: 194-0, 16h.41m
    fanboy-thirdparty_social: 68-0, 16h.45m
    ublock-annoyances: 4807-4, 1d.11h.10m
    FIN-0: 2081-2, 1d.11h.9m
  default: 
    user-filters: 287-0, never
    ublock-filters: 32021-2767, 1d.11h.14m
    ublock-badware: 4007-5, 1d.11h.13m
    ublock-privacy: 285-2, 9d.17h.19m
    ublock-abuse: 76-4, 9d.17h.19m
    ublock-unbreak: 1908-1, 1d.11h.12m
    ublock-quick-fixes: 566-0, 16h.42m
    easylist: 64357-625, 2d.23h.30m
    easyprivacy: 30822-2096, 3d.12h.58m
    urlhaus-1: 11492-0, 16h.44m
    plowe-0: 3668-365, 9d.17h.19m
filterset (user): [array of 301 redacted]
switchRuleset: 
  added: [array of 11 redacted]
hostRuleset: 
  added: [array of 607 redacted]
urlRuleset: 
  added: [array of 107 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  contextMenuEnabled: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: {{date}}
supportStats: 
  allReadyAfter: 1839 ms (selfie)
  maxAssetCacheWait: 654 ms
popupPanel: 
  blocked: 18
  blockedDetails: 
    soranews24.com: 3
    amazon-adsystem.com: 1
    chartbeat.com: 1
    criteo.net: 1
    doubleclick.net: 1
    facebook.net: 2
    getpocket.com: 1
    googletagmanager.com: 1
    logly.co.jp: 1
    parsely.com: 1
    polldaddy.com: 1
    quantserve.com: 1
    teads.tv: 1
    twitter.com: 1
    wp.com: 1
```
</details>

**Comment by knakamura8** [comment]
Any update on this?

**Comment by krystian3w** [comment]
Every day in cat mouse tribe.

**Comment by Yuki2718** [comment]
> Any update on this?

What's the matter? Our filters should have been working for last few days. Make sure you don't have another blocker *in any network layer* and your filters are up-to-date.

> Every day in cat mouse tribe.

*Apparently* they gave up, but we will keep monitoring.

**Comment by knakamura8** [comment]
>What's the matter? Our filters should have been working for last few days.
When I posted on December 20th, they were not (tested on several different networks with fully up-to-date browsers before asking).  Checking the latest batch of commits, now it is working.  Thanks!

**Comment by krisu5** [comment]
I tested with Brave, checked the hosts file (no blocks there), its own blocker disabled, reseted uBlock settings and updated filters: still not working for me.

Same with my Firefox, but I try with clean profile soon-ish.

**Comment by krystian3w** [comment]
In chrome maybe needed is disable heavy ads protection:

```yml
chrome://settings/content/ads
```

**Comment by Yuki2718** [comment]
> ```yaml
> chrome://settings/content/a
> ```

I doubt that.

**Comment by krystian3w** [comment]
`/a` is invalid

**Comment by troysjanda** [comment]
I don't have ETP enabled, In fact I have custom selected with nothing checked,  soranews24.com it does not load the images except the first two. not other addons, on a test profile.

below are my troubleshooting information section in Ubo using Windows 10 19045.2364 Enterprise

`
uBlock Origin: 1.46.1b4
Firefox: 108
filterset (summary): 
  network: 89185
  cosmetic: 115832
  scriptlet: 21781
  html: 898
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/UBOXPI: 443-0, 6h.1m
    https://raw.githubusercontent.com/troysjanda/MyBlockLists/master/yahoocomplete.txt: 476-0, 6h.1m
    adguard-spyware-url: 871-4, 4h.2m
    block-lan: 44-0, 6h.1m
    fanboy-annoyance: 84588-459, 6h.1m
    ublock-annoyances: 4832-9, 6h.1m
  default: 
    user-filters: 5-0, never
    ublock-filters: 32307-143, 6h.1m
    ublock-badware: 4223-0, 6h.1m
    ublock-privacy: 305-0, 6h.1m
    ublock-abuse: 77-0, 6h.1m
    ublock-unbreak: 1926-5, 6h.1m
    ublock-quick-fixes: 446-1, 6h.1m
    easylist: 61198-205, 6h.1m
    easyprivacy: 30858-1212, 6h.1m
    urlhaus-1: 7225-0, 6h.1m
filterset (user): [array of 6 redacted]
trustedset: 
  added: [array of 53 redacted]
hostRuleset: 
  added: [array of 3 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoCommentFilterTemplate: none
  cnameIgnoreRootDocument: false
  extensionUpdateForceReload: true
  filterAuthorMode: true
  filterOnHeaders: true
  updateAssetBypassBrowserCache: true
  userResourcesLocation: [redacted]
supportStats: 
  allReadyAfter: 433 ms (selfie)
  maxAssetCacheWait: 232 ms

`

**Comment by Yuki2718** [comment]
Cause: Xpi uBo Personal Filters

**Comment by troysjanda** [comment]
What specific filter as I dont see any filter for that site

**Comment by Yuki2718** [comment]
`doubleclick.net^$important`

**Comment by troysjanda** [comment]
I see thanks however not going to remove that filter. what would be a good filter to exempt that site from that filter.

**Comment by Yuki2718** [comment]
Nothing, unless https://github.com/uBlockOrigin/uBlock-issues/issues/2437#issuecomment-1369294505 is somehow accepted. Just turn whole JS off via no-scripting switch on the site.

**Comment by Yuki2718** [comment]
Oh, did you mean exempt the site from the rule? Then
`||doubleclick.net^$important,domain=~soranews24.com`

**Comment by troysjanda** [comment]
>Oh, did you mean exempt the site from the rule? Then
>||doubleclick.net^$important,domain=~soranews24.com

yes to alllow on that site to fix breakage

**Comment by troysjanda** [comment]
> ||doubleclick.net^$important,domain=~soranews24.com

So I then would add other domain separated with a comma to exempt more if this happen again. or how to add more exemptions to the same rule

**Comment by mapx-** [comment]
`||doubleclick.net^$important,domain=~soranews24.com|~another.site`

**Comment by troysjanda** [comment]
Thank you.

**Comment by krystian3w** [comment]
or

```adb
||doubleclick.net^$important,domain=com,denyallow=soranews24.com
```

I don't learned new `to=` and `from=` in real cases.
