### ISSUE TITLE
facebook.com: ads

### ISSUE THREAD

**Issue by DavidW-GIT** [uBlockOrigin/uAssets#18008]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.facebook.com/?sk=h_chr`

### Category

ads

### Description

ads appearing in the last ~3 days with facebook, seems to be related to a recent facebook change.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![facebookads](https://github.com/uBlockOrigin/uAssets/assets/66330313/2dead83a-5cc4-460e-b0ed-8ecaa8d224b5)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 93335
 cosmetic: 40538
 scriptlet: 17415
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 1-0, never
  easylist: 67176-46, 6h.2m
  easyprivacy: 32240-45, 6h.2m
  plowe-0: 3742-936, 6h.2m
  ublock-abuse: 70-0, 6h.2m
  ublock-badware: 7118-128, 6h.2m
  ublock-filters: 33091-88, 6h.2m
  ublock-privacy: 394-74, 6h.2m
  ublock-quick-fixes: 246-11, 6h.2m
  ublock-unbreak: 2016-36, 6h.2m
  urlhaus-1: 6711-1, 6h.2m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 258 ms
 maxAssetCacheWait: 113 ms
popupPanel: 
 blocked: 5
 network: 
  facebook.com: 1
  doubleclick.net: 4
 cosmetic: 
  ##.AdBox
  ##.post-ads
```
</details>

**Comment by Daxy7** [comment]
Pretty sure it was addressed and fixed here https://github.com/uBlockOrigin/uAssets/issues/3367#issuecomment-1536846966. Purge all caches and click update now in the filters section of uBO.

**Comment by DavidW-GIT** [comment]
complete deletion of appdata\local\google folder, and re-setup of chrome with reinstallation of uBO, and a re-download of caches, unfortuantely, does not resolve the issue.

**Comment by DavidW-GIT** [comment]
re-purge of caches and re-download seems to have resolved. Not sure what changed in the last 6h.2m from report to "now"

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 112
filterset (summary): 
 network: 93363
 cosmetic: 40533
 scriptlet: 17394
 html: 0
listset (total-discarded, last-updated): 
 default: 
  user-filters: 1-0, never
  easylist: 67206-46, 1m
  easyprivacy: 32240-45, 1m
  plowe-0: 3742-936, 1m
  ublock-abuse: 70-0, 1m
  ublock-badware: 7119-128, 1m
  ublock-filters: 33070-91, 1m
  ublock-privacy: 394-74, 1m
  ublock-quick-fixes: 245-11, 1m
  ublock-unbreak: 2012-36, 1m
  urlhaus-1: 6711-1, 1m
filterset (user): [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 258 ms
 maxAssetCacheWait: 113 ms
popupPanel: 
 blocked: 5
 network: 
  facebook.com: 1
  doubleclick.net: 4
 cosmetic: 
  ##.AdBox
  ##.post-ads
```
</details>

**Comment by stephenhawk8054** [comment]
Please continue to comment in this thread: https://github.com/uBlockOrigin/uAssets/issues/3367

**Comment by krystian3w** [comment]
It is best to wait until the uBo icon turns from yellowish to brownish/redish/maroonish.
