### ISSUE TITLE
goplay.be: ads

### ISSUE THREAD

**Issue by firstaawi** [uBlockOrigin/uAssets#18432]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.goplay.be/video/blind-gekocht/blind-gekocht-s5/blind-gekocht-s5-aflevering-9`

### Category

ads

### Description

ads are limited blocked. most of the times only the first ad is blocked, and when you receive a second or third ad further in the video, the video keeps playing until the 2nd/3rd ad and can't pass trought it.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 95998
 cosmetic: 52034
 scriptlet: 19047
 html: 0
listset (total-discarded, last-updated): 
 added: 
  TUR-0: 14105-11, 3d.20h.35m
 default: 
  user-filters: 1-0, never
  NLD-0: 2883-12, 2d.18h.51m
  easylist: 66847-71, 2d.16h.50m
  easyprivacy: 31107-62, 17h.35m
  plowe-0: 3724-939, 7d.19h.19m
  ublock-abuse: 69-0, 6d.19h.49m
  ublock-badware: 7257-131, 17h.36m
  ublock-filters: 33425-134, 15h.33m
  ublock-privacy: 383-74, 5h.50m
  ublock-quick-fixes: 191-5, 7h.51m
  ublock-unbreak: 2033-39, 15h.32m
  urlhaus-1: 6687-0, 17h.34m
filterset (user): [array of 1 redacted]
trustedset: 
 added: [array of 7 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 924 ms (selfie)
 maxAssetCacheWait: 334 ms
popupPanel: 
 blocked: 13
 network: 
  goplay.be: 1
  doubleclick.net: 1
  gemius.pl: 2
  google.com: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  gstatic.com: 1
  imasdk.googleapis.com: 1
  mediahuis.be: 1
  onthe.io: 1
  pbstck.com: 1
```
</details>

**Comment by stephenhawk8054** [comment]
Need

```adb
goplay.be#@#+js(json-prune, ads)
goplay.be##+js(json-prune, ads time_events_url)
```

@BPower0036

**Comment by BPower0036** [comment]
Fixed @stephenhawk8054

**Comment by firstaawi** [comment]
I removed cash & performed update. But still have the same problem.

**Comment by stephenhawk8054** [comment]
The update might not come to you yet. You can use the filters above in the meantime.

**Comment by BPower0036** [comment]
@firstaawi @gorhill made our own website CDN as the `contentURL` instead of direct public list with timestamps: `https://raw.githubusercontent.com/EasyDutch-uBO/EasyDutch/gh-pages/EasyDutch.txt`. So updates get only published two times a day.
