### ISSUE TITLE
chat.nrj.fr: detection

### ISSUE THREAD

**Issue by PegHorse** [uBlockOrigin/uAssets#18442]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable external filter lists, or I have verified that the issue still occurs without enabling external filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

The issue was fixed a while ago but now it's detected again.

Main URL : `https://chat.nrj.fr`
I am redirected to this page
`https://chat.nrj.fr/Content/AB/AB.html`

### Category

detection

### Description

Go to chat.nrj.fr with an account, once you're logged, Ublock is detected.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.49.2
Chromium: 114
filterset (summary): 
 network: 170077
 cosmetic: 231997
 scriptlet: 40750
 html: 0
listset (total-discarded, last-updated): 
 added: 
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 67696-97, 6m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 91263-20817, 6m
  adguard-generic: 71466-752, 6m
  adguard-mobile: 8261-58, 6m
  adguard-social: 20488-1528, 6m
  adguard-spyware: 43636-1264, 6m
  adguard-spyware-url: 1053-3, 6m
  block-lan: 47-0, 6m
  fanboy-cookiemonster: 47404-47404, 6m
  fanboy-social: 16068-16068, 6m
  ublock-annoyances: 5062-277, 6m
  adguard-cookies: 25806-25806, now
  adguard-popup-overlays: 22617-22617, now
  adguard-mobile-app-banners: 4294-4294, now
  adguard-other-annoyances: 12816-12816, now
  adguard-widgets: 2163-2163, now
  easylist-annoyances: 3839-3839, now
  easylist-chat: 125-9, now
  easylist-newsletters: 6086-6086, now
  easylist-notifications: 2629-2629, now
 default: 
  user-filters: 1-0, never
  FRA-0: 28205-70, 6m
  easylist: 67018-1031, 6m
  easyprivacy: 30999-13762, 6m
  plowe-0: 3733-1137, 6m
  ublock-badware: 7329-375, 6m
  ublock-filters: 33495-4198, 6m
  ublock-privacy: 397-66, 6m
  ublock-quick-fixes: 197-8, 6m
  ublock-unbreak: 2033-141, 6m
  urlhaus-1: 6301-0, 6m
filterset (user): [array of 1 redacted]
trustedset: 
 added: [array of 69 redacted]
 removed: 
  edge-scheme
switchRuleset: 
 added: [array of 4 redacted]
modifiedUserSettings: 
 cloudStorageEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
 allReadyAfter: 1039 ms (selfie)
 maxAssetCacheWait: 565 ms
popupPanel: 
 blocked: 2
 network: 
  123multimedia.com: 1
  googletagmanager.com: 1
```
</details>

**Comment by PegHorse** [comment]
Detection enforced :
If you go now to the main page, they are trying to force you to install Google Chrome
After signed in, they are detecting Adblocker.

**Comment by PegHorse** [comment]
You have closed both Threads while it's not fixed

**Comment by stephenhawk8054** [comment]
![image](https://github.com/user-attachments/assets/06045d60-6d6b-41bd-9503-977b1d627538)

It's fixed here: https://github.com/uBlockOrigin/uAssets/commit/75ec88074330bd88a1f448093c408ff992b541e2

**Comment by PegHorse** [comment]
It's not fixed, i have force the update but it's still displaying

![image](https://github.com/user-attachments/assets/1f118afb-3e0d-4600-b42c-f898a093b5bd)
