### ISSUE TITLE
[nsfw] manga-crab.com: detection

### ISSUE THREAD

**Issue by Mixuco** [uBlockOrigin/uAssets#19444]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://manga-crab.com/series/urban-doctor/capitulo-0/`

### Category

detection

### Description

Detects the page the blocker 

### Other extensions used

![Screenshot_2023-08-23-23-36-30-364-edit_com kiwibrowser browser](https://github.com/uBlockOrigin/uAssets/assets/85970971/5d1e09c6-3acc-4752-8ae5-ad2170025259)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Chromium Mobile: 116
filterset (summary):
 network: 102265
 cosmetic: 36139
 scriptlet: 18708
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  adguard-mobile: 8564-33, now
  easylist: 69640-15999, now
  easyprivacy: 33308-72, now
  plowe-0: 3726-1139, now
  spa-0: 3749-278, now
  spa-1: 5474-292, now
  ublock-badware: 7759-147, now
  ublock-filters: 34666-415, now
  ublock-privacy: 535-7, now
  ublock-quick-fixes: 283-106, now
  ublock-unbreak: 2121-37, now
  urlhaus-1: 5966-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1002 ms (selfie)
 maxAssetCacheWait: 139 ms
popupPanel:
 blocked: 13
 network:
  manga-crab.com: 2
  cloudflareinsights.com: 1
  doubleclick.net: 1
  googlesyndication.com: 6
  googletagmanager.com: 1
  wp.com: 1
  youtube.com: 1
 extended:
  ##ins.adsbygoogle
```
</details>

**Comment by stephenhawk8054** [comment]
Which country are you when accessing the site?

**Comment by BlazeFTL** [comment]
> Which country are you when accessing the site?

Try Spain

**Comment by Mixuco** [comment]
Mexico

**Comment by stephenhawk8054** [comment]
I cannot access the website: https://github.com/uBlockOrigin/uAssets/assets/66517106/77e71fdc-c95c-4925-a16f-95e5eebaf7a1

**Comment by Mixuco** [comment]
Well, no problem if you can not thank you very much

**Comment by dportvine** [comment]
`Chromium Mobile: 116` Which exact browser?

I can't reproduce.

<details>
<summary>Screen</summary>

![2023-08-24_105911](https://github.com/uBlockOrigin/uAssets/assets/111344219/d8d245b7-48c7-4f20-acc5-e530d4bf0c3d)
</details>

@stephenhawk8054 
>I cannot access the website:

I use Urban VPN Proxy

**Comment by mapx-** [comment]
FF desktop => blocked
brave => I can access the page, no detection; similar in emulation mode in brave.

**Comment by stephenhawk8054** [comment]
Ah right, I can access now using chromium, but cannot reproduce the issue either.

**Comment by mapx-** [comment]
right, 

this filter has the effect of killing the warning

`/wp-content/plugins/uncopy/*`

@Mixuco 

enable `uBlock filters – Annoyances`

**Comment by stephenhawk8054** [comment]
Even though the anti-adb can be closed, but it re-appears when refreshing the site, so should it be fixed in main list?

**Comment by garry-ut99** [comment]
Oh, I misunderstood his point, I thought he means the anti-adblock still appears, even despite fixed.

**Comment by Mixuco** [comment]
Yes, there is a solution for that.
