### ISSUE TITLE
3bmeteo.com: nuisance

### ISSUE THREAD

**Issue by enzor00** [uBlockOrigin/uAssets#19594]
### Prerequisites

- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/124740436/235392297-c4fc6290-73a6-4a70-96a9-3f6a7683f21d.png), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.3bmeteo.com/meteo/calitri`

### Category

nuisance

### Description

When I open the site a black square appears on the right side, if I go down with the page the black square moves to the bottom right side

### Other extensions used

Dark Reader
TWP - Translate Web Pages

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

https://github.com/uBlockOrigin/uAssets/assets/138575369/c5b1c284-60c7-451c-9e1f-b879a660e26b
https://github.com/uBlockOrigin/uAssets/assets/138575369/f8f7bf54-7559-4b35-809f-99a99375d127

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.51.0
Firefox: 117
filterset (summary):
 network: 108141
 cosmetic: 127704
 scriptlet: 22251
 html: 1028
listset (total-discarded, last-updated):
 added:
  adguard-social: 21312-163, now
  adguard-cookies: 27432-35, now
  adguard-popup-overlays: 23776-860, now
  adguard-mobile-app-banners: 4588-7, now
  adguard-other-annoyances: 13347-11, now
  adguard-widgets: 2296-1, now
 default:
  user-filters: 0-0, never
  ublock-filters: 35398-482, now
  ublock-badware: 7908-0, now
  ublock-privacy: 570-0, now
  ublock-unbreak: 2170-1, now
  ublock-quick-fixes: 243-3, now
  easylist: 70023-773, now
  easyprivacy: 33266-727, now
  urlhaus-1: 5806-0, now
  plowe-0: 3724-2, now
  ITA-0: 10503-20, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 453 ms (selfie)
 maxAssetCacheWait: 181 ms
popupPanel:
 blocked: 13
 network:
  3bmeteo.com: 4
  amazon-adsystem.com: 1
  cloudflareinsights.com: 4
  doubleclick.net: 1
  googletagmanager.com: 1
  imrworldwide.com: 2
 extended:
  ###adwallpaper
  ###admasthead
  ###adv_nativ_sopracartina
  ###adv_outbrain_AR_1_sottocartina
  ###ads_container
  ###admputop
  ###fb-root:not(body):not(html)
  ##.gpt_top
```
</details>

**Comment by mapx-** [comment]
it's fixed by the regional list `it: EasyList Italy`

Try updating all your lists

**Comment by enzor00** [comment]
> it's fixed by the regional list `it: EasyList Italy`
> 
> Try updating all your lists

I cleared the filter cache and updated them but the problem persists

**Comment by mapx-** [comment]
disable adguard- lists and test again

**Comment by enzor00** [comment]
It didn't work
