### ISSUE TITLE
Photopea.com - breakage

### ISSUE THREAD

**Issue by photopea** [uBlockOrigin/uAssets#19697]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

When my users visit my website www.Photopea.com , and they allow uBlock Origin to have a total control of a website (read and rewrite the information), your extension modifies the look of Photopea and it is impossible to use it (the right side is cut-off).

The issue was reported to me by dozens of users, but I am afraid it happens to hundreds of thousands, who simply dont report it and think that Photopea is broken. Here are three of them

https://github.com/photopea/photopea/issues/6024
https://github.com/photopea/photopea/issues/5878
https://github.com/photopea/photopea/issues/5844

### A specific URL where the issue occurs.

www.Photopea.com

### Steps to Reproduce

1. Open www.Photopea.com with the uBlock Origin extension
2. It looks differently than without it

### Expected behavior

The website should be usable

### Actual behavior

The website is not usable

### uBO version

latest

### Browser name and version

latest Chrome

### Operating System and version

Windows 10

**Comment by photopea** [comment]
This is related to people who pay for Photopea Premium (the "Account" button at the top is green), who do not see any ads. You still stretch the UI for them.

**Comment by photopea** [comment]
I think I have fixed it. Since you are re-setting window.innerWidth, I have switched to the property window.screen.width .

BTW. I am tolerating the ad-blockers for now. But you should not apply any "cracks" to my source code to allow people use my Premium features (full-screen interface) for free. That is basically the same as piracy, and you are facilitating it.

**Comment by HelderRocket** [comment]
It happens to me with the Edge browser. While I use an ad blocker (Adblock), I have the page in the exclusions list. And in fact, even though I have the extension disabled, the ads still don't come up.

![image](https://github.com/uBlockOrigin/uAssets/assets/104467221/03f8f309-9edf-472b-902d-568ecac8cb04)

I thought it might be some additional browser settings, however also in those settings I have the page excluded and it still does not appear (Enhanced security and tracking prevention).

![image](https://github.com/uBlockOrigin/uAssets/assets/104467221/b8195d2a-efaa-4577-9507-1dc38031c6f3)

**Comment by okiehsch** [comment]
>  But you should not apply any "cracks" to my source code to allow people use my Premium features (full-screen interface) for free.

We don't circumvent paywalls, see https://github.com/uBlockOrigin/uAssets#readme

We do add filters to circumvent anti adblock walls and we don't check if the same filter breaks your paywall too.

**Comment by photopea** [comment]
What do you mean by "make the anti-blocker dismissable, we could remove the anti-blocker filters"? What are anti-blockers and anti-blocker filters?

BTW. what would be the right way to detect, that your extension is in charge of a website, so we can ask our users to disable the ad blocker? Do you provide any interface for this?

**Comment by photopea** [comment]
> It happens to me with the Edge browser. While I use an ad blocker (Adblock), I have the page in the exclusions list. And in fact, even though I have the extension disabled, the ads still don't come up.
> 
> https://github.com/uBlockOrigin/uAssets/assets/104467221/03f8f309-9edf-472b-902d-568ecac8cb04
> 
> I thought it might be some additional browser settings, however also in those settings I have the page excluded and it still does not appear (Enhanced security and tracking prevention).
> 
> https://github.com/uBlockOrigin/uAssets/assets/104467221/b8195d2a-efaa-4577-9507-1dc38031c6f3

Actually, the [AdBlock](https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom) extension is lying to their users. You tell it to dont do ad blocking on some website, but they still block ads (that is what you did). I recommend to switch to better ad blockers (AdBlock Plus, uBlock Origin) which do allow you to turn it off for a specific domain. 

I even wrote this article, which should help people, who cannot see ads in Photopea properly: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by photopea** [comment]
You still have not fixed it. There are lot of people struggling because of your extension, and I have to tell each one explicitly to turn your extension off :(  This is just for today:

https://github.com/photopea/photopea/issues/6117
https://www.reddit.com/r/photopea/comments/17e9l9e/so_i_finally_succumbed_and_paid_for_photopea_only/

**Comment by photopea** [comment]
@MasterKia  You still have not fixed it. There are lots of people struggling because of your extension, and I have to tell each one explicitly to turn your extension off :(  This is just for today:

https://github.com/photopea/photopea/issues/6117
https://www.reddit.com/r/photopea/comments/17e9l9e/so_i_finally_succumbed_and_paid_for_photopea_only/
