### ISSUE TITLE
anitube.vip: breakage

### ISSUE THREAD

**Issue by kalil6** [uBlockOrigin/uAssets#20572]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/19976), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.anitube.vip/video/281221`

### Category

breakage

### Description

The section [div class="videos_players" bis_skin_checked="1"] of the site is removed, cutting access to the video players link.

### Other extensions used

tampermonkey

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

not wrking
![a0](https://github.com/uBlockOrigin/uAssets/assets/78522183/fa9fd0e9-cb0b-4cc6-9d85-2c8b13e535da)

working
![a01](https://github.com/uBlockOrigin/uAssets/assets/78522183/d8c0429b-3a48-42c8-bde8-52cc95b436ad)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 105745
 cosmetic: 47208
 scriptlet: 19280
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75175-16, 9m
  easyprivacy: 32854-64, 9m
  plowe-0: 3722-1074, 9m
  spa-1: 5722-66, 12m
  ublock-badware: 7435-135, 9m
  ublock-filters: 35231-175, 9m
  ublock-privacy: 663-5, 9m
  ublock-quick-fixes: 153-90, 9m
  ublock-unbreak: 2135-33, 9m
  urlhaus-1: 10950-0, 9m
filterset (user): [empty]
trustedset:
 added: [array of 2 redacted]
 removed:
  chrome-scheme
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 423 ms (selfie)
 maxAssetCacheWait: 154 ms
popupPanel:
 blocked: 2
 network:
  arc.io: 1
  googletagmanager.com: 1
 extended:
  ##+js(set-constant, ATESTADO, 1)
  ##+js(abort-on-property-read, exoJsPop101)
  ##+js(set-constant, adBlockDetected, noopFunc)
  ##+js(abort-current-script, document.createElement, script)
  ##+js(abort-current-script, parseInt, break;case $.)
  ##+js(addEventListener-defuser, , break;case $.)
```
</details>

**Comment by mapx-** [comment]
I fixed the arc button (left bottom) and the disqus forum.
No other breakage on my side. Check if you have some wrong custom filter or other blocking extension.

**Comment by D4niloMR** [comment]
If you click in `Player SD` this happen even with uBO disabled

**Comment by kalil6** [comment]
discus forum fix confirmed.
the problem of [div class="videos_players" bis_skin_checked="1"] still persist. No custom filters or other blocking extensions being used.
Currently using userscript manager extension Tempermonkey, with an youtube script on it. But even disabling tempermonkey the problem still persist.

@D4niloMR
Same here, but the site works normally in incognito, can only imagine the ad blocking is the problem

**Comment by D4niloMR** [comment]
> can only imagine the ad blocking is the problem

If the problem persists with uBlock Origin off, the problem is not the uBO.

**Comment by kalil6** [comment]
Seem the problem was another extension called "urban VPN Proxy". Even with the extension turned off still it would interfere with some sites like pixiv, and anime-sharing. 
Well at least we got the fix for discus.

**Comment by kalil6** [comment]
Seem the problem was another extension called "urban VPN Proxy". Even with the extension turned off still it would interfere with some sites like pixiv, and anime-sharing.
Well at least we got the fix for discus.
