### ISSUE TITLE
mapchart.net: ads

### ISSUE THREAD

**Issue by Zenphia** [uBlockOrigin/uAssets#21305]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I forced an update of my filter lists. (Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://www.mapchart.net/`

### Category

ads

### Description

Shows an "Advertisement" box when editing a map that appears above the map and below "Report a bug", even though there aren't any ads displayed there.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.52.2
Chromium: 117
filterset (summary):
 network: 103573
 cosmetic: 44020
 scriptlet: 19482
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 26-0, never
  easylist: 75324-16, 1h.16m
  easyprivacy: 33072-65, 1h.16m
  plowe-0: 3776-1137, 1h.16m
  ublock-badware: 7589-138, 1h.16m
  ublock-filters: 35847-174, 1h.16m
  ublock-privacy: 928-12, now
  ublock-quick-fixes: 170-9, 1h.16m
  ublock-unbreak: 2156-31, 1h.16m
  urlhaus-1: 9915-0, 1h.16m
filterset (user): [array of 24 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 122 ms (selfie)
 maxAssetCacheWait: 44 ms
popupPanel:
 blocked: 3
 network:
  pirsch.io: 1
  uniconsent.com: 2
 extended:
  ##.fillpicker-container.sp-palette-only.sp-light.sp-container > …
  ##[href="#save-my-maps"]
  ##.ad-cont-top.ad-cont.row
  ##footer
  ##.ad-cont.col-md-12
  ##.pre-modal-footer.modal-part
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  #@#[id^="div-gpt-ad"]
  #@#div[id^="div-gpt-"]
  ##+js(set-constant, rwt, noopFunc)
```
</details>

**Comment by mapx-** [comment]
add

`mapchart.net##.row:has-text(Adv)`

@ryanbr

**Comment by garry-ut99** [comment]
A typo, in EasyList should be `:-abp-contains` instead of `:has-text`

**Comment by whiplashoo** [comment]
Hi, I am the developer of mapchart.net. 

This filter is now removing all the main content of the UI:

![image](https://github.com/uBlockOrigin/uAssets/assets/9117427/14ea0b81-5fc4-4c7b-800d-8181df30d7b8)

**It essentially removes all rows (.row) that contain the substring `Adv`, including unrelated content, like:**

- Any mention of "Advanced", like in the advanced settings modal, removes the whole row.
- There is a map page called World Advanced. Any mention of it removes the full row.
- Above each ad, I added a <span> with the text "Advertisements", to make sure that users can distinguish that they are seeing an ad. While I have no issue with the label and the accompanying ad being removed, this filter now REMOVES THE WHOLE PARENT ROW, which includes the website's main UI.

Can this be reverted or made more specific to not break the entire site? I woke up today with numerous e-mails from confused users, asking why they can't suddenly use the website.

Again, please do remove the ads; I can also help with making this filter more specific. But currently, **this breaks the whole website by removing unrelated content from the page.**

**Comment by mapx-** [comment]
fixed in uBO, I'll notify easylist maintainer to fix in easylist too

**Comment by whiplashoo** [comment]
OK, thank you. I will wait until easylist is also updated, and check again to see which elements are removed.

**Comment by whiplashoo** [comment]
I believe this is still not ideal. I am using the word "Advertisements" above ads to signify to users that they are seeing an ad:

![14678](https://github.com/uBlockOrigin/uAssets/assets/9117427/c5f431cd-930b-4d39-94b6-ba1a8e69d51a)

With the current rule (`mapchart.net#?#.row:-abp-contains(Advertisement)`), **any parent row of this label is removed, making legit content unavailable to the users.**

Can't it be a more specific rule to only remove the label and not the content of any parent row (.row)? Here is the exact HTML for that label:

<div class="lbl" style="display: block;">Advertisements</div>
