### ISSUE TITLE
uBlock blocking Tapas' "Mark All (Messages) Read" button from working

### ISSUE THREAD

**Issue by MegaMawilite** [uBlockOrigin/uAssets#21472]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is NOT an issue with [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

On Tapas' message board (where it likes to advertise their webcomics despite nobody wanting it) there is a button to Mark All Read, which is very useful to not end up with dozens of "messages" (ads) in one week or so.
However, since I adopted uBlock as my adblocker, the button stopped working, and only wants to work if I disable uBlock's ads filter list. It *might* be a filter list issue but I truly have no idea since this is a button and it shouldn't be considered an ad by any means.

### A specific URL where the issue occurs.

https://tapas.io/inbox/message

### Steps to Reproduce

1. I'd say create an account to get access to the message board, and wait like one day: You'll get two ads in the message board.
2. Try to click the Mark All Read button

### Expected behavior

Page should refresh and all messages marked as "New" should have their "New" mark removed, furthermore, if your only notifications were those messages, the notification red dot should be gone.

### Actual behavior

Page refreshes but nothing else happens: The "New"s are still there, the notification dot is still present, etc.

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 124399
 cosmetic: 53355
 scriptlet: 19847
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 101-0, never
  FRA-0: 28852-39, 6h.15m
  easylist: 75866-77, 51m
  easyprivacy: 33117-331, 51m
  plowe-0: 3779-1159, 12d.9h.34m
  ublock-badware: 7633-153, 3m
  ublock-filters: 36435-422, 2m
  ublock-privacy: 949-13, 3m
  ublock-quick-fixes: 116-5, 5m
  ublock-unbreak: 2175-36, 5m
  urlhaus-1: 11025-0, 5h.14m
filterset (user): [array of 101 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 337 ms (selfie)
 maxAssetCacheWait: 143 ms
```
</details>

**Comment by stephenhawk8054** [comment]
Can you test these filters?

```adb
://www.*/firebase.js|$script,3p,to=com,badfilter
://www.*/firebase.js|$script,3p,to=com|~gstatic.com
```

**Comment by MegaMawilite** [comment]
@stephenhawk8054 I will test those out but I can't have a result until Tapas send an advertising message again (so about a day from now)

**Comment by MegaMawilite** [comment]
I didn't see the "troubleshooting information" before, whoops--

anyway, here are the details

uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 124401
 cosmetic: 53371
 scriptlet: 19847
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 102-0, never
  FRA-0: 28852-39, 20h.1m
  easylist: 75885-77, 1h
  easyprivacy: 33116-331, 1h
  plowe-0: 3779-1159, 12d.23h.20m
  ublock-badware: 7633-153, 13h.49m
  ublock-filters: 36435-422, 13h.49m
  ublock-privacy: 949-13, 13h.49m
  ublock-quick-fixes: 116-5, 1h
  ublock-unbreak: 2175-36, 13h.51m
  urlhaus-1: 11025-0, 19h
filterset (user): [array of 103 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 337 ms (selfie)
 maxAssetCacheWait: 143 ms
popupPanel:
 blocked: 15
 network:
  adjust.com: 1
  ads-twitter.com: 1
  amazon-adsystem.com: 1
  amplitude.com: 1
  appboycdn.com: 1
  branch.io: 1
  daum.net: 1
  doubleclick.net: 1
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  quantserve.com: 1
  sc-static.net: 1
  tiktok.com: 1
  ultra-rv.com: 1

**Comment by MegaMawilite** [comment]
well, I could test and see and I can confirm the filters StephenHawk8054 worked! Thanks!

**Comment by MegaMawilite** [comment]
(I don't know if I should close the issue or keep it open tbh, but my problem has been resolved)

**Comment by OFS-Razgriz** [comment]
I have this same issue and the filter list changes didn't seem to fix the problem. I tried both updating my current filter lists and also adding the filters supplied in this thread to my filter lists. Here is the auto-generated output I get when I go to submit an issue (I figured it would be better to re-open this issue than it would be to start a brand new one for the same problem).

<details>

```yaml
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 281403
 cosmetic: 91151
 scriptlet: 37705
 html: 1143
listset (total-discarded, last-updated):
 added:
  adguard-generic: 81416-827, 21m
  adguard-mobile: 8920-102, 21m
  adguard-spyware-url: 1365-92, 21m
  adguard-spyware: 81714-18017, 21m
  block-lan: 55-0, 21m
  curben-phishing: 79570-28, 21m
  fanboy-thirdparty_social: 69-0, 22m
  dpollock-0: 11614-494, 22m
 default:
  user-filters: 2-0, never
  ublock-filters: 37343-3603, 1h.28m
  ublock-badware: 7647-11, 1h.28m
  ublock-privacy: 947-4, 1h.28m
  ublock-unbreak: 2222-2, 1h.28m
  ublock-quick-fixes: 120-0, 1h.28m
  easylist: 76133-2496, 1h.28m
  easyprivacy: 33123-991, 1h.28m
  urlhaus-1: 12355-0, 21m
  plowe-0: 3782-1, 22m
filterset (user): [array of 3 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 757 ms (selfie)
 maxAssetCacheWait: 316 ms
popupPanel:
 blocked: 16
 network:
  adjust.com: 1
  ads-twitter.com: 1
  amazon-adsystem.com: 1
  amplitude.com: 1
  appboycdn.com: 2
  branch.io: 1
  daum.net: 1
  doubleclick.net: 1
  facebook.net: 1
  google-analytics.com: 1
  googletagmanager.com: 1
  quantserve.com: 1
  sc-static.net: 1
  tiktok.com: 1
  ultra-rv.com: 1
 extended:
  ##.go-to-top
```
</details>
