### ISSUE TITLE
pomofocus.io: detection

### ISSUE THREAD

**Issue by crlsszz** [uBlockOrigin/uAssets#21859]
### Prerequisites

- [X] This is **NOT** a [YouTube](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [Facebook](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [Twitch](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin (uBO) along with other content blocker extensions.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [ ] I did not answer truthfully to **ALL** the above checkpoints.

### URL address of the web page

`https://pomofocus.io/`

### Category

detection

### Description

Getting the following pop-up message: "Ad blocker detected. To use Pomofocus, please disable the ad blocker for this site or consider upgrading to premium. Thank you for your support🙏"

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="502" alt="Screen Shot 2024-01-09 at 11 30 11 AM" src="https://github.com/uBlockOrigin/uAssets/assets/156076757/d5110d88-20d0-4481-abc4-111556eecd4e">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.54.0
Chromium: 120
filterset (summary):
 network: 115527
 cosmetic: 44210
 scriptlet: 20013
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76876-12, 29m
  easyprivacy: 43397-32, 29m
  plowe-0: 3784-1165, now
  ublock-badware: 7769-137, 29m
  ublock-filters: 36465-203, 29m
  ublock-privacy: 951-7, 29m
  ublock-quick-fixes: 216-51, 29m
  ublock-unbreak: 2187-31, 29m
  urlhaus-1: 9890-0, 29m
filterset (user): [empty]
trustedset:
 added: [array of 17 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1440 ms (selfie)
 maxAssetCacheWait: 439 ms
popupPanel:
 blocked: 3
 network:
  buysellads.net: 1
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##a[href^="https://go.nordvpn.net/aff"] > img
```
</details>

**Comment by stephenhawk8054** [comment]
Fixed already: https://github.com/uBlockOrigin/uAssets/commit/c6436e806bcbfa657e7003089d34d55981eff5db

Wait about 5-6 hours, the filter lists will automatically update for you

**Comment by 801chrisp** [comment]
Hello.  I would like to report that I'm still experiencing issues with this website despite the changes you've made @stephenhawk8054 -- see below:

### Screenshot(s)
<details>
<summary>Screenshot(s)</summary>



![2024-01-10 08_47_52-45_00 - Time to focus! and 3 more pages - Personal - Microsoft​ Edge](https://github.com/uBlockOrigin/uAssets/assets/24196711/e001c5ef-9228-466f-bd32-2cff0741708e)



</details>

### Configuration
<details>

```yaml
uBlock Origin: 1.55.0
Chromium: 120
filterset (summary):
 network: 115866
 cosmetic: 44236
 scriptlet: 20027
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 76938-12, now
  easyprivacy: 43407-32, now
  plowe-0: 3786-1166, now
  ublock-badware: 7770-137, now
  ublock-filters: 36394-128, now
  ublock-privacy: 963-7, now
  ublock-quick-fixes: 225-51, now
  ublock-unbreak: 2187-31, now
  urlhaus-1: 10170-0, now
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1726 ms
 maxAssetCacheWait: 39 ms
 cacheBackend: browser.storage.local
popupPanel:
 blocked: 2
 network:
  buysellads.net: 1
  googletagmanager.com: 1
 extended:
  ##a[href^="https://go.nordvpn.net/aff"] > img
  ##+js(no-xhr-if, googlesyndication)
```
</details>

**Comment by v1gnesh** [comment]
I'm still seeing the pop-up.

<details>
<summary>Config</summary>

```uBlock Origin: 1.55.0
Firefox: 115
filterset (summary):
 network: 316816
 cosmetic: 244668
 scriptlet: 50195
 html: 2223
listset (total-discarded, last-updated):
 added:
  http://sbc.io/hosts/hosts: 0-0, never
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76370-76370, 2d.3h.53m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 1h.34m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt: 1421-7, 4d.14h.38m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt: 159088-155637, 3h.52m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-1, 3h.52m
  https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-35, 4d.14h.38m
  https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt: 1-0, 4d.14h.38m
  https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt: 34-0, 4d.14h.38m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95323-95282, 4d.3h.18m
  https://winhelp2002.mvps.org/hosts.txt: 8729-317, 4d.14h.38m
  https://www.fanboy.co.nz/enhancedstats.txt: 0-0, 4d.3h.18m
  [23 lists not shown]: [too many]
 default:
  user-filters: 1108-12, never
  ublock-filters: 36982-482, 1h.34m
  ublock-badware: 7798-16, 1h.33m Δ
  ublock-privacy: 959-88, 1h.33m Δ
  ublock-unbreak: 2233-1, 1h.33m Δ
  ublock-quick-fixes: 191-1, 1h.34m
  easylist: 77047-1031, 1h.33m Δ
  easyprivacy: 43409-1280, 1h.33m Δ
  urlhaus-1: 9905-0, 1h.34m
  plowe-0: 3784-1704, 6d.15h.31m
filterset (user): [array of 1098 redacted]
trustedset:
 added: [array of 6 redacted]
 removed:
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 141 redacted]
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 added: [array of 6951 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
urlRuleset:
 added: [array of 388 redacted]
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 0
 requestLogMaxEntries: 5000
 webrtcIPAddressHidden: true
hiddenSettings:
 autoUpdatePeriod: 7
 filterAuthorMode: true
supportStats:
 allReadyAfter: 1001 ms (selfie)
 maxAssetCacheWait: 649 ms
 cacheBackend: indexedDB
```
</details>

![image](https://github.com/uBlockOrigin/uAssets/assets/234149/107fc019-4b6a-40b5-9746-43dedcf15d6a)

**Comment by stephenhawk8054** [comment]
@v1gnesh Can you open new tab > reproduce the issue and on that page > click on uBO icon > &#128172; [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on `Troubleshooting Information` and copy paste it here?

**Comment by v1gnesh** [comment]
Perhaps that was it. I needed to reopen the tab. 
Can I add a comment here if I still face this (seems to be working right now after relaunch)?

<details>
<summary>Properly collected troubleshooting info</summary>

```uBlock Origin: 1.55.0
Firefox: 115
filterset (summary):
 network: 316815
 cosmetic: 244657
 scriptlet: 50196
 html: 2223
listset (total-discarded, last-updated):
 added:
  http://sbc.io/hosts/hosts: 0-0, never
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 76370-76370, 2d.4h.44m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 2h.25m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt: 1421-7, 4d.15h.28m
  https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt: 159088-155648, 4h.42m
  https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-1, 4h.43m
  https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt: 2735-35, 4d.15h.28m
  https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt: 1-0, 4d.15h.29m
  https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt: 34-0, 4d.15h.28m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 95323-95282, 4d.4h.8m
  https://winhelp2002.mvps.org/hosts.txt: 8729-317, 4d.15h.29m
  https://www.fanboy.co.nz/enhancedstats.txt: 0-0, 4d.4h.8m
  [23 lists not shown]: [too many]
 default:
  user-filters: 1108-12, never
  ublock-filters: 36982-482, 2h.24m
  ublock-badware: 7798-16, 50m Δ
  ublock-privacy: 959-88, 50m Δ
  ublock-unbreak: 2233-1, 50m Δ
  ublock-quick-fixes: 191-1, 2h.25m
  easylist: 77046-1031, 50m Δ
  easyprivacy: 43409-1280, 50m Δ
  urlhaus-1: 9905-0, 2h.25m
  plowe-0: 3784-1704, 6d.16h.22m
filterset (user): [array of 1098 redacted]
trustedset:
 added: [array of 6 redacted]
 removed:
  chrome-scheme
  edge-scheme
  moz-extension-scheme
  opera-scheme
  vivaldi-scheme
  wyciwyg-scheme
switchRuleset:
 added: [array of 141 redacted]
 removed:
  no-large-media: behind-the-scene false
hostRuleset:
 added: [array of 6953 redacted]
 removed:
  behind-the-scene * * noop
  behind-the-scene * image noop
  behind-the-scene * 3p noop
  behind-the-scene * inline-script noop
  behind-the-scene * 1p-script noop
  behind-the-scene * 3p-script noop
  behind-the-scene * 3p-frame noop
urlRuleset:
 added: [array of 388 redacted]
userSettings:
 advancedUserEnabled: true
 largeMediaSize: 0
 requestLogMaxEntries: 5000
 webrtcIPAddressHidden: true
hiddenSettings:
 autoUpdatePeriod: 7
 filterAuthorMode: true
supportStats:
 allReadyAfter: 1001 ms (selfie)
 maxAssetCacheWait: 649 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 12
 network:
  pomofocus.io: 5
  buysellads.net: 1
  google.com: 3
  googletagmanager.com: 1
  stripe.com: 2
 extended:
  ##a[href^="https://go.nordvpn.net/aff"] > img
  ##+js(no-xhr-if, adsbygoogle, length:10)
  ##+js(no-xhr-if, pagead2.googlesyndication.com)
  ##+js(no-xhr-if, pagead2.googlesyndication.com, true)
```
</details>

**Comment by stephenhawk8054** [comment]
@v1gnesh You are using a highly modified configuration with too many custom filters (I suspect 1 of your custom filters is related to the site).

Test it again in another profile with only uBO default settings and update the filter lists.

**Comment by v1gnesh** [comment]
Yes, I'm using it in hard mode, and zap out a lot of UI junk.
Thank you, sincerely, for responding and helping uBO in general.
