### ISSUE TITLE
bild.de: detection

### ISSUE THREAD

**Issue by RichardEb** [uBlockOrigin/uAssets#22484]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in blocker or [DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking) (standalone or through a VPN) is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://m.bild.de/adblockwall.html`

### Category

detection

### Description

Access to website is blocked

### Other extensions used

None

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.55.0
Firefox Mobile: 122
filterset (summary):
 network: 193643
 cosmetic: 41807
 scriptlet: 19956
 html: 2098
listset (total-discarded, last-updated):
 added:
  adguard-spyware: 100502-32800, now
  block-lan: 56-0, now
 default:
  user-filters: 0-0, never
  ublock-filters: 38175-422, 41m Δ
  ublock-badware: 7859-14, 41m Δ
  ublock-privacy: 971-1, 41m Δ
  ublock-unbreak: 2264-1, 41m Δ
  ublock-quick-fixes: 131-0, 41m Δ
  adguard-mobile: 9196-133, now
  easylist: 81045-16623, 41m Δ
  easyprivacy: 50196-850, 41m Δ
  urlhaus-1: 7485-0, 41m
  plowe-0: 3782-1, now
  DEU-0: 7258-406, 41m
filterset (user): [empty]
userSettings:
 cloudStorageEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 464 ms (selfie)
 maxAssetCacheWait: 204 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  bild.de: 4
  bing.com: 2
  cxense.com: 1
  demdex.net: 2
  doubleclick.net: 1
  facebook.net: 1
  googletagmanager.com: 1
  ioam.de: 1
  kameleoon.eu: 1
  outbrain.com: 1
 extended:
  ##+js(no-setTimeout-if, offsetParent)
  ##+js(abort-on-property-read, SmartAdServerASMI)
  ##+js(json-prune, adBlockWallEnabled)
  ##+js(set-constant, __NUXT__.state.advertisement.adBlockWallEnab…
  ##+js(addEventListener-defuser, load, adBlock)
```
</details>

**Comment by ItsProfessional** [comment]
https://github.com/uBlockOrigin/uAssets/issues/21987

**Comment by RichardEb** [comment]
@ItsProfessional this is not a duplicate of a 1 month old report. It worked well until today. It was never broken since 1 month

**Comment by mapx-** [comment]
fixed minutes ago
https://github.com/uBlockOrigin/uAssets/commit/94b5ebe65c90caaa97666c593dfc3368b0c696cc

**Comment by ItsProfessional** [comment]
Apparently the issue is back: https://new.reddit.com/r/uBlockOrigin/comments/1975v6o/comment/kwbwkka/?context=3
Can anyone reproduce?

**Comment by mapx-** [comment]
no issue on my end
