### ISSUE TITLE
picrew.me: ads / breakages / detection

### ISSUE THREAD

**Issue by crunchmunchguy** [uBlockOrigin/uAssets#23005]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://picrew.me/en/image_maker/346059`

### Category

ads

### Description

All image makers on picrew are showing ads. This was not happening before, and only started today. The ads are sorta glitchy, but still there.

### Other extensions used

I have privacy badger, if that counts. 

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 126141
 cosmetic: 45662
 scriptlet: 18990
 html: 1717
listset (total-discarded, last-updated):
 default:
  user-filters: 6-0, never
  ublock-filters: 37581-173, 4m Δ
  ublock-badware: 7981-14, 4m Δ
  ublock-privacy: 761-0, 4m Δ
  ublock-unbreak: 2309-0, 4m Δ
  ublock-quick-fixes: 225-0, 4m Δ
  easylist: 82808-642, 4m Δ
  easyprivacy: 50395-833, 4m Δ
  urlhaus-1: 8495-0, 4m
  plowe-0: 3765-1, now
filterset (user): [array of 6 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 952 ms (selfie)
 maxAssetCacheWait: 86 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 67
 network:
  picrew.me: 1
  adingo.jp: 1
  criteo.net: 1
  doubleclick.net: 1
  googlesyndication.com: 1
  html-load.com: 60
  sentry.io: 2
 extended:
  ##.play-Imagemaker_Footer
```
</details>

**Comment by mapx-** [comment]
```
picrew.me##+js(no-fetch-if, /static\.criteo\.net|adsbygoogle/, length:150000-150200)
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=picrew.me
*$frame,redirect-rule=noopframe,domain=picrew.me
*$script,xhr,redirect-rule=noopjs,domain=picrew.me
*$image,redirect-rule=1x1.gif,domain=picrew.me
@@*$ghide,domain=picrew.me
picrew.me##ins.adsbygoogle:style(height: 1px !important; visibility: hidden !important;)
picrew.me##[src="about:blank"]
```

**Comment by mapx-** [comment]
@crunchmunchguy it was fixed, wait for the automatic updating of your filter lists

**Comment by crunchmunchguy** [comment]
The same thing that was happening to Rackover was also happening to me, but updating my lists fixed it lol. Thank you!

**Comment by JobcenterTycoon** [comment]
Its "Ad-Shield" crap. Fixed here: https://github.com/uBlockOrigin/uAssets/commit/b5302e1a82dc329d3ba531a4da7492f13c69c206 to get the fix directly: https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-filters&manual=1

**A alternate way to block Ad-Shield ads is --> [microShield](https://github.com/List-KR/microShield) <--. Its a special userscript designed to block Ad-Shield related ads.**

**Comment by Rackover** [comment]
I updated the list clicking the link (it didn't appear to change anything in the ublock configuration window, but i suppose it did something behind the stages). I still have the same problem (ads everywhere, and whenever I put my filters back on, nag screen + self destruction)

**Comment by DesperatePea** [comment]
Thank you, force-updating my list seems to have fixed it for me.

**Comment by im-not-sure-yet** [comment]
i have this same issue of the glitchy ads and i tried to click the link to update my list but it didn't do anything... i also tried pasting the filters in to my list and it didn't work... i also only have adblock and ads killer plus other than ublock origin so i don't know if that's whats interfering with it...

**Comment by JobcenterTycoon** [comment]
Disable the other blocker and test again.

**Comment by Rackover** [comment]
Cleared the cache, tried clicking the link again, then checked picrew again - exactly the same stuff.
Disabled my filters too. If I add the filter i posted above, it gets detected - if I don't, i have ads everywhere

Edge version 122.0.2365.92
Ublock origin Version 1.56.0

With the filter posted above enabled:
![image](https://github.com/uBlockOrigin/uAssets/assets/33836535/8ba1f5f0-0c74-465d-b294-3aab20b51e76)

Without:
![image](https://github.com/uBlockOrigin/uAssets/assets/33836535/b1743696-46de-4d00-a283-17ebba338dc4)

**Comment by JobcenterTycoon** [comment]
Test `@@||html-load.com^$image,domain=picrew.me`

On Edge i get unstable results, even with adblocker disabled i get sometimes the error page.

**Comment by Rackover** [comment]
No effect

**Comment by apertureatomics** [comment]
facing this exact issue, no other blockers installed, all filter lists updated, i clicked the link and it didnt seem to do anything.

**Comment by JobcenterTycoon** [comment]
Try the microShield userscript which i mentioned in https://github.com/uBlockOrigin/uAssets/issues/23005#issuecomment-2012260490

I tried the userscript on Edge and it works perfectly. Should fix the issue. At the moment the issue is not 100% fixable with uBlock Origin alone.

**Comment by apertureatomics** [comment]
thank you sm the userscript did it!

**Comment by Rackover** [comment]
Sorry I don't want to sound entitled or mean, but i would rather keep my setup with just uBlockOrigin rather than installing another extension like greaseMonkey/tamperMonkey and importing userscripts in it :(

I have a feeling blocking ads without disturbing the browsing experience is uBlockOrigin's objective so I figure this problem (adshield detection/bypass) will maybe be fixed at some point?

In the meantime would it please be possible to reopen this issue for the sake of tracking 🙏
While there is a workaround involving installing other extensions it seems the base issue is not yet fixed as of today

**Comment by JobcenterTycoon** [comment]
Updated. Should be avaiable within ~5 hours.
