### ISSUE TITLE
chromewebstore.google.com: nuisance

### ISSUE THREAD

**Issue by SampeiNihira** [uBlockOrigin/uAssets#24371]
Web site where the issue described in the title occurs:

https://chromewebstore.google.com/

obviously if you use a browser that is not chrome.
I insert image that displays the pop-up:

![1](https://github.com/uBlockOrigin/uBOL-home/assets/44166263/4f549fb3-740f-4b55-a8f4-f8abb4f76bf3)

The pop-up is not blocked even with **full filtering** selected.

**Comment by garry-ut99** [comment]
This is already fixed in: `AdGuard – Other Annoyances`, but uBlock Lite doesn't contain `AdGuard Annoyances` filters, related issues:
- https://github.com/uBlockOrigin/uBOL-home/discussions/137
- https://github.com/uBlockOrigin/uBOL-home/issues/127

**Comment by stephenhawk8054** [comment]
```adb
chromewebstore.google.com##[role="dialog"][aria-labelledby="promo-header"]
```

@ryanbr

**Comment by stephenhawk8054** [comment]
@gorhill Actually even with Edge, I don't think uBOL can filter `https://chromewebstore.google.com/` ? But I don't know why uBOL still shows block counter in the screenshot.

**Comment by garry-ut99** [comment]
>  Actually even with Edge, I don't think uBOL can filter `https://chromewebstore.google.com/` ? 

Seems so, as I added some rules into uBOL and they don't work in Chromium & Firefox on that site.

> But I don't know why uBOL still shows block counter in the screenshot.

Maybe OP interacted with the page, as page doesn't show any block counter after loading, but the block counter appears after some interaction with the page, for example after pressing 9dot menu button:  
[SCREENSHOOT](https://github.com/uBlockOrigin/uAssets/assets/72945564/cb1fdc10-85a1-4c8f-badf-d7ddba382416).

However on OP's screenshoot the 9dot button is covered by the pop-up, so maybe he interacted with page in another way.

Strange thing is that I'm unable to reproduce the pop-up OP reported, in Windows + Chromium & Edge, I get it only in Firefox.

**Comment by SampeiNihira** [comment]
So basically,how is it possible to eliminate the pop-up with uBLock Origin Lite in non Chrome browsers (I use Edge)?

Also because when I opened the issue I already had Easy List - Other Annoyances enabled otherwise I didn't open this issue........

![1](https://github.com/uBlockOrigin/uAssets/assets/44166263/1ee8d2ab-5dde-4e1e-a0d3-37ec2c606eea)

**Comment by garry-ut99** [comment]
Because Chromium-based browsers's restrictions do not allow extensions to access webstore page:
- https://adguard.com/kb/adguard-browser-extension/protected-pages/#chromium-browser-restrictions
- https://github.com/AdguardTeam/AdguardFilters/issues/161017#issuecomment-1715421887
