### ISSUE TITLE
Lookmovie2.to adblock detection

### ISSUE THREAD

**Issue by DesperatePea** [uBlockOrigin/uAssets#24462]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.lookmovie2.to
```

### Description

Loads a 10 second cooldown on adblock detection at the beginning of the video.

### Other extensions used

I still do not care about cookies
uBlacklist
sponsorblock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="1361" alt="bilde" src="https://github.com/uBlockOrigin/uAssets/assets/73502428/bebd2fb6-72f8-4644-925c-a5f57b9fc26a">

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.58.0
Firefox: 127
filterset (summary):
 network: 210212
 cosmetic: 253544
 scriptlet: 52602
 html: 2118
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 80255-139, 4d.22h.8m
  https://raw.githubusercontent.com/laylavish/uBlockOrigin-HUGE-AI-Blocklist/main/list.txt: 3809-33, 23h.7m
  https://secure.fanboy.co.nz/fanboy-annoyance_ubo.txt: 100147-23457, 5d.20h.9m
  adguard-generic: 82569-4128, 4d.10h.9m
  adguard-spyware-url: 1581-122, 4d.10h.9m
  curben-phishing: 513-0, 6h.2m
  adguard-social: 23070-1664, 4d.10h.9m
  fanboy-thirdparty_social: 68-19, 5d.20h.9m
  fanboy-cookiemonster: 67569-67552, 1d.1h.7m
  fanboy-social: 16384-16356, 1h.4m
  ublock-annoyances: 5907-260, 2h.56m Δ
  adguard-spyware: 69680-32132, 4d.10h.9m
  [5 lists not shown]: [too many]
 default:
  user-filters: 64-9, never
  ublock-filters: 39310-453, 2h.56m Δ
  ublock-badware: 9173-1, 2h.56m Δ
  ublock-privacy: 1025-6, 2h.56m Δ
  ublock-unbreak: 2445-7, 2h.56m Δ
  ublock-quick-fixes: 135-4, 2h.56m Δ
  easylist: 86753-2290, 2h.56m Δ
  easyprivacy: 52751-320, 2h.56m Δ
  urlhaus-1: 16970-5, 6h.2m
  plowe-0: 3543-1004, 10d.23h.32m
  NOR-0: 3858-165, 8h.27m
filterset (user): [array of 64 redacted]
trustedset:
 added: [array of 27 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 217 ms (selfie)
 maxAssetCacheWait: 142 ms
 cacheBackend: indexedDB
```
</details>

**Comment by JobcenterTycoon** [comment]
Fixed in `uBlock filters – Annoyances`

**Comment by DesperatePea** [comment]
Im sorry, but the problem is still there. I updated ublock annoyances filter but its still happening.

**Comment by JobcenterTycoon** [comment]
The filter need a few hours until they are avaiable as a update.

**Comment by stephenhawk8054** [comment]
The countdown appears even when you don't use any extensions. I don't think it's considered as detection but paywall. Users can use custom filter in this: https://github.com/uBlockOrigin/uAssets/issues/21071#issuecomment-2145426247

**Comment by stephenhawk8054** [comment]
Also

> - [X] I verified that this issue is not a duplicate. (Search [here](https://github.com/uBlockOrigin/uAssets/issues) to find out.)

**Comment by D4niloMR** [comment]
I think we can add the scriptlet filter in uBO annoyances since we are speeding the timer anyway.
