### ISSUE TITLE
[Anti-adblock] LCPDFR.com

### ISSUE THREAD

**Issue by NocFA** [uBlockOrigin/uAssets#2486]
### URL(s) where the issue occurs

`http://www.lcpdfr.com/`

### Describe the issue

Ad block getting caught, anti-adblock not working.

### Screenshot(s)

https://i.imgur.com/JdV2ZbT.png

### Versions

- Browser/version: Vivaldi/1.15.1147.42 based on Chrome/65.0.3325.183
- uBlock Origin version: 1.16.8

### Settings

- Default UBo settings.

### Notes

Appears the html element changes and gets randomised every time you refresh the page, that's all I know.

**Comment by okiehsch** [comment]
Fixed in `uBO-annoyances`.

**Comment by Alex4567890** [comment]
It is currently not fixed. I have default filtes + Fanboy’s Annoyance + uBlock filters – Annoyances. Browser: Google Chrome Version 88.0.4324.146.

**Comment by Alex4567890** [comment]
I have also tested with **Fanboy's Annoyance** turned off.

**Comment by okiehsch** [comment]
You get the anti adblock warning in the screenshot of the OP?

I can't reproduce.

**Comment by uBlock-user** [comment]
`||g17media.com^$script,redirect=noopjs,domain=lcpdfr.com` is present in uBlock Annoyances list, so works with the list activated.

**Comment by okiehsch** [comment]
He said that the has that list enabled.

> I have default filtes + Fanboy’s Annoyances + uBlock filters – Annoyances.

**Comment by uBlock-user** [comment]
He will have to investigate why it doesn't work for him.

**Comment by Alex4567890** [comment]
I know it is present, but it still pops up. Using the element picker to remove it works, but I just wanted to let you know in case you wanted to add to the filters in order to prevent it from happening.

**Comment by okiehsch** [comment]
We can't reproduce, so there is nothing to do really
The only difference between our setups is the regional list, I can see that your regional list blocks one request that is not usally blocked.
![image](https://user-images.githubusercontent.com/16838044/107193579-47f0dd80-69ef-11eb-9f02-400f2dea23f9.png)

Does it work for you if you disable that list?
I assume that you have it enabled.

**Comment by Alex4567890** [comment]
I do not have it enabled.

**Comment by okiehsch** [comment]
Well, then I don't know.

**Comment by Alex4567890** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/78655307/107197008-07e42780-69fc-11eb-823f-b4621f03f41c.png)

**Comment by Alex4567890** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/78655307/107197197-424dc480-69fc-11eb-8252-3eca0b0a2062.png)

**Comment by uBlock-user** [comment]
Reset to default settings, force update all the lists that require updates, then activate uBlock Annoyances list.

**Comment by Alex4567890** [comment]
> Reset to default settings, force update all the lists that require updates, then activate uBlock Annoyances list.
I didn't have any custom settings, I removed the annoyance filters, purged all caches, clicked "purge all caches" and activated uBlock Annoyances list. 
I still encounter tit.

**Comment by Alex4567890** [comment]
I disabled uBO on the website and I there aren't any ads and the message still appears.

**Comment by Alex4567890** [comment]
on Firefox I don't encounter any of the things that I enlisted. (Fanboy's Annoyance + uBlock filters -- Annoyances)
