### ISSUE TITLE
[Anti-adblock] haaretz.co.il

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#2548]
### URL(s) where the issue occurs

`https://www.haaretz.co.il/.premium-1.2880808`

### Describe the issue

Redirects to anti-adblock page

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/41324383-73691102-6e71-11e8-9674-2dba341496d2.png)

### Versions

- Browser/version: Chrome 69
- uBlock Origin version: 1.16.8

### Settings

All default.

**Comment by okiehsch** [comment]
This is alread fixed in the regional list, so no need to add it to `uBO-filters`.
![unbenannt](https://user-images.githubusercontent.com/16838044/41325335-f6d54112-6eb9-11e8-8efa-08db5afb2fe3.PNG)

**Comment by jspenguin2017** [comment]
I thought EasyList doesn't fix anti-adblock. And how come EasyList has extended syntax?

**Comment by okiehsch** [comment]
Well, `EasyList Hebrew does`, they also use extended syntax for quite some time.

**Comment by krystian3w** [comment]
https://github.com/easylist/EasyListHebrew/commit/e688ae6dbe51dd485581a0d2756d862413c7ee65
