### ISSUE TITLE
eodev.com: ads

### ISSUE THREAD

**Issue by electr0dev** [uBlockOrigin/uAssets#26157]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://eodev.com/` 

### Category

ads

### Description

This site prevents you from using adblocker and displays video ads. The brand named Brainly in the US. The ad is only valid on Brainly for Turkey(Eodev).

### Other extensions used

I dont used any other extensions.

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Ca4pture](https://github.com/user-attachments/assets/8b5f7efb-03bf-45b6-994b-111fb27953c2)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.61.0
Chromium: 130
filterset (summary):
 network: 137032
 cosmetic: 49797
 scriptlet: 23109
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 40653-250, now
  ublock-badware: 11975-1, now
  ublock-privacy: 1533-22, now
  ublock-unbreak: 2508-0, now
  ublock-quick-fixes: 232-4, now
  easylist: 79118-603, now
  easyprivacy: 53276-639, now
  urlhaus-1: 18775-0, now
  plowe-0: 3530-0, now
filterset (user): [empty]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 456 ms (selfie)
 maxAssetCacheWait: 151 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 15
 network:
  eodev.com: 3
  adlightning.com: 1
  cloudflareinsights.com: 1
  datadome.co: 1
  doubleclick.net: 2
  ex.co: 1
  google.com: 1
  googletagmanager.com: 1
  opti-digital.com: 2
  rubiconproject.com: 1
  sentry-cdn.com: 1
 extended:
  ##.brn-ads-box
  ##[data-testid="brainly_ads_placeholder"]
  ##+js(no-setTimeout-if, trigger, 0)
```
</details>

**Comment by stephenhawk8054** [comment]
Fixed in "uBlock filters – Annoyances" list

**Comment by electr0dev** [comment]
Its not fixed. Im tried with Annoyances list now, its not working.

**Comment by stephenhawk8054** [comment]
Wait about 5-6 hours and update the filter lists again.

**Comment by stephenhawk8054** [comment]
You can also add this as your custom filter in the meantime:

```adb
brainly.*,eodev.com,nosdevoirs.fr##+js(set-local-storage-item, simple-funnel-name, $remove$)
```

Click on uBO icon > ⚙ [Dashboard button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > ✓ Apply changes > Open new tab and test again.

You might need to refresh the site twice.
