### ISSUE TITLE
moovitapp.com: popups

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#29612]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/27415), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/27472) report. _These sites MUST be reported by clicking their **respective links**_.
- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [x] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [x] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [x] I have turned off all other extensions and the issue still persists. (exception "[Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers)").
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [x] I have verified that the browser I am using is up to date with no pending updates.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://moovitapp.com/index/tr/toplu_ta%C5%9F%C4%B1ma-Dr_Mustafa_Gen%C3%A7ay_Anadolu_Lisesi-Hatay-site_206416166-6128`

### Category

popups

### Description

This popup makes it difficult to view the page on mobile

### Browser name and version

Firefox mobil

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Image](https://github.com/user-attachments/assets/09d76802-e561-47b5-95cc-46aa8dd32e6e)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.65.0
Firefox Mobile: 141
filterset (summary):
 network: 164854
 cosmetic: 157546
 scriptlet: 32994
 html: 2369
listset (total-discarded, last-updated):
 added:
  adguard-cookies: 34865-74, now
  ublock-cookies-adguard: 5074-74, now
  adguard-social: 24299-45, now
  adguard-popup-overlays: 27910-873, now
  adguard-mobile-app-banners: 6274-99, now
  adguard-other-annoyances: 14815-303, now
  adguard-widgets: 2928-22, now
 default:
  user-filters: 22-0, never
  ublock-filters: 41242-82, 9m
  ublock-badware: 11351-32, 9m
  ublock-privacy: 3366-3, 9m
  ublock-unbreak: 2737-1, 9m
  ublock-quick-fixes: 308-13, 9m
  adguard-mobile: 11246-66, 9m
  easylist: 78963-281, 9m
  easyprivacy: 54386-64, 9m
  urlhaus-1: 28975-0, 9m
  plowe-0: 3423-976, 9m
  TUR-0: 8836-109, 9m
filterset (user): [array of 12 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 2227 ms
 maxAssetCacheWait: 1175 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  moovitapp.com: 1
  ay.delivery: 1
  cookielaw.org: 1
  doubleclick.net: 1
  google.com: 3
  googlesyndication.com: 3
 extended:
  ##div[id^="div-gpt-"]:not([style^="width: 1px; height: 1px; posi…
  ##[id^="div-gpt-ad"]:not([style^="width: 1px; height: 1px; posit…
  ##.ads-wrapper
  ##.gpt-ad
  ##.bannerAd
  #@#div[id^="div-gpt-"]
  #@#[id^="div-gpt-ad"]
  ##+js(prevent-fetch, doubleclick)
```
</details>

**Comment by mapx-** [comment]
```adb
moovitapp.com##.blur-filter.footer
moovitapp.com##.poi-banner
moovitapp.com##body:style(overflow: auto !important)
```

**Comment by Alex-302** [comment]
Fixed in AdGuard Mobile App Banners.

**Comment by muralito** [comment]
For URL https://moovitapp.com/index/es-419/transporte_p%C3%BAblico-line-427-Montevideo-1672-3320919-96469862-0 is not yet fixed in Firefox desktop. EasyList updated just before posting this.

> [Adblock Plus 1.1]
! Title: EasyPrivacy
! Expires: 6 days (update frequency)
! Last modified: Wed, 13 Aug 2025 13:23:33 +0000
! Diff-Path: ../patches/2025.8.13.1407.patch#easyprivacy
! Diff-Expires: 317 minutes
! *** easylist:template_header.txt ***



I added those 3 lines to MyFilters

> moovitapp.com##.blur-filter.footer
moovitapp.com##.poi-banner
moovitapp.com##body:style(overflow: auto !important)

but it didn't solve the issue. the site still blocks the usage.

https://github.com/user-attachments/assets/66886f77-4c31-4e2f-b178-3723e6f1a797

**Comment by stephenhawk8054** [comment]
Can you screenshot your list of extensions to here?

**Comment by muralito** [comment]
> Can you screenshot your list of extensions to here?

<img width="724" height="566" alt="Image" src="https://github.com/user-attachments/assets/70dd30a7-7b06-44f8-af44-c799d3979f74" />

**Comment by stephenhawk8054** [comment]
Turn off all other extensions (except uBO), open new tab and test again.

**Comment by Alex-302** [comment]
@muralito Is AG Mobile Ads filter enabled?

**Comment by muralito** [comment]
> Turn off all other extensions (except uBO), open new tab and test again.

With all extensions disabled except uBO it works as expected.
After trying some combinations, starting and restarting Firefox, it seems that is related only to having EFF Privacy Badger enabled. With EFF Privacy Badger disabled and all other extensions enabled it also works as expected.

**Comment by muralito** [comment]
> [@muralito](https://github.com/muralito) Is AG Mobile Ads filter enabled?

I'm using Firefox on linux desktop.
I haven't used Ad Guard at least since it started with the "aceptable ads" policy and I have found uBlock Origin a lot of years ago.

**Comment by stephenhawk8054** [comment]
@muralito `AG mobile ads` is a filter list inside uBO. You are probably thinking about Adblock Plus tho.

**Comment by muralito** [comment]
> [@muralito](https://github.com/muralito) `AG mobile ads` is a filter list inside uBO. You are probably thinking about Adblock Plus tho.

Sorry. :-) No, AG mobile ads list is not enabled. I haven't seen those settings in a long time. uBO and the enabled lists just worked fine for me until yesterday.

https://github.com/user-attachments/assets/b83c3448-b6ca-47fa-867f-1a6c091eecf6
