### ISSUE TITLE
everyeye.it: nuisance

### ISSUE THREAD

**Issue by SalvatoreNoschese** [uBlockOrigin/uAssets#29884]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/27415), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/27472) report. _These sites MUST be reported by clicking their **respective links**_.
- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [x] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [x] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [x] I have turned off all other extensions and the issue still persists. (exception "[Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers)").
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [x] I have verified that the browser I am using is up to date with no pending updates.
- [x] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://tech.everyeye.it/
https://auto.everyeye.it/
```

### Description

Hi, tried with all filter enabled, tried also via custom filter, bit I still have issue with this website.
So, tried to install "I don't care about cookies" or "I still don't care about cookies" and with both, finally, issue is fixed.

Obviously, I prefer to remove those extension and use only ublock 😊

### Browser name and version

Pixel 10 > Android 16 > org.mozilla.firefox > 142.0.1

### Other extensions used

Just this:
https://github.com/user-attachments/assets/65702328-821a-4968-9e7a-61bfbaec0c38

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml


```
</details>

**Comment by mapx-** [comment]
already fixed by EasyList/uBO – Cookie Notices => enable it

**Comment by SalvatoreNoschese** [comment]
As I wrote, I tried to enable (also to enable all filter). But issue remain here.

**Comment by mapx-** [comment]
go again to one of those pages
go into uBO settings, support tab, copy and paste here: Troubleshooting Information

**Comment by SalvatoreNoschese** [comment]
<details>

```yml
uBlock Origin: 1.65.0
Firefox Mobile: 142
filterset (summary):
 network: 422190
 cosmetic: 391816
 scriptlet: 61987
 html: 2867
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 added:
  adguard-generic: 86084-4128, 18m
  adguard-spyware-url: 2243-133, 18m
  block-lan: 86-0, 18m
  curben-phishing: 137132-48, 18m
  adguard-cookies: 35062-78, 6m
  ublock-cookies-adguard: 5088-74, 6m
  fanboy-cookiemonster: 46228-3907, 6m
  ublock-cookies-easylist: 5088-5088, 6m
  adguard-social: 24397-49, 20m
  fanboy-social: 17402-820, 20m
  fanboy-thirdparty_social: 69-18, 20m
  adguard-popup-overlays: 28110-947, 20m
  [45 lists not shown]: [too many]
 default:
  ublock-filters: 41429-75, 21m
  ublock-badware: 11147-31, 21m
  ublock-privacy: 3438-3, 6m Δ
  ublock-unbreak: 2742-1, 6m Δ
  ublock-quick-fixes: 315-12, 21m
  adguard-mobile: 11321-104, 21m
  easylist: 78251-1352, 6m Δ
  easyprivacy: 54443-155, 21m
  urlhaus-1: 30875-5, 21m
  plowe-0: 3420-1330, 21m
  ITA-0: 6327-131, 21m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 514 ms (selfie)
 maxAssetCacheWait: 334 ms
 cacheBackend: indexedDB
```

</details>

**Comment by SalvatoreNoschese** [comment]
As u can see...
https://github.com/user-attachments/assets/fccaefc6-8230-41f3-9511-63228278e1b8
https://github.com/user-attachments/assets/fb3c4acf-2d78-466e-b4a5-89dfaac69a04

Thanks for help ✌️

**Comment by mapx-** [comment]
I re-tested in FF android, working fine on my end.

- reset uBO to defaults, then enable only EasyList/uBO – Cookie Notices (both lists)
- disable any other extension
- test again

**Comment by stephenhawk8054** [comment]
I can't reproduce either with only additional `EasyList/uBO – Cookie Notices` list.

**Comment by SalvatoreNoschese** [comment]
Thanks for useful replies.
After some test, I confirm work as expected, but come back if I enable also this 😅

<details>

<img width="1080" height="2424" alt="Image" src="https://github.com/user-attachments/assets/fa0125f1-3782-4b81-a8cb-f338862486b1" />

</details>

**Comment by stephenhawk8054** [comment]
@mapx- Looks like AG excludes due to this issue: https://github.com/AdguardTeam/AdguardFilters/issues/191969 . I can reproduce.

**Comment by mapx-** [comment]
me too, @Alex-302 could you take a look at it ?

**Comment by stephenhawk8054** [comment]
We'll need `trusted-click`, I'll add the filters.

**Comment by stephenhawk8054** [comment]
I mean I can reproduce the images breakage in AG's issue thread. We'll need exclusions and `trusted-click`.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/f87d48da64a1351dbc80ff5eb0a2018392f0a4d3

**Comment by crafty991** [comment]
The problem has not yet been resolved. If you look at the bottom left, you can still see the cookie symbol, and when I browse, a black screen appears after a couple of seconds.

<details><summary>Screenshot</summary>
https://github.com/user-attachments/assets/2847796e-316f-408c-a425-05ea83fc3f5d
</details>

**Comment by crafty991** [comment]
@stephenhawk8054 @mapx- The problem has not yet been resolved. If you look at the bottom left, you can still see the cookie symbol, and when I browse, a black screen appears after a couple of seconds.

<details><summary>Video</summary>

https://github.com/user-attachments/assets/ba601e6f-d79a-4cdd-8f11-ed9c851097a0

</details>
