### ISSUE TITLE
poczta.o2.pl: detection

### ISSUE THREAD

**Issue by OloTka** [uBlockOrigin/uAssets#30175]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/30158), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://www.github.com/uBlockOrigin/uAssets/discussions/27472) report. _These sites MUST be reported by clicking their **respective links**_.
- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [x] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/d22aca5f-58db-4ab3-9b31-8e65a7aeff2e), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I have disabled the `Developer mode` in uBO Lite's settings and the issue still persists.
- [x] I have verified that the issue still exists after using the [`Optimal` or `Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [x] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [x] I have turned off all other extensions and the issue still persists.
- [x] If this is about a breakage or detection, I have verified that it is caused by uBO Lite and isn't a site or browser issue.
- [x] I have verified that the browser I am using is up to date with no pending updates.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://poczta.o2.pl/w/mails?folder=classic.main`

### Category

detection

### Description

o2 discovers ads blocking software.

### Browser name and version

Chrome - 140.0.7339.129

### Other extensions used

Deepl translator

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

```yaml
name: uBlock Origin Lite
version: 2025.921.2008
browser: Chrome 140 (win)
filtering:
 site: complete
 default: optimal
rulesets:
 ublock-filters
 easylist
 easyprivacy
 pgl
 ublock-badware
 urlhaus-full
 adguard-spyware-url
 annoyances-cookies
 stevenblack-hosts
 ubol-tests
 pol-0
console:
 [0925.0726]insertCSS/Error: No frame with id 148 in tab with id 431789034
```

**Comment by mapx-** [comment]
report here: https://github.com/MajkiIT/polish-ads-filter/issues

**Comment by krystian3w** [comment]
I don't think so to by fixed MajkiIT hands: https://github.com/MajkiIT/polish-ads-filter/issues?q=sort%3Aupdated-desc%20state%3Aclosed%20label%3A%22adblock%20detect%22%20label%3Aodrzucone%20-commenter%3AMajkiIT%20-commenter%3AOlegwukr

**Comment by mapx-** [comment]
fixed
https://github.com/uBlockOrigin/uAssets/commit/ade4d7721979ae08946526efdeec64f0de3bd76b

**Comment by OloTka** [comment]
It looks like it's not working, still the same message to turn off adblock. 

<details>

<img width="373" height="430" alt="Image" src="https://github.com/user-attachments/assets/a232ea2e-bad1-4735-abc5-ab1736b37af2" />

</details>

It might be I'm doing something not right although there is no option in uBlock Lite to refresh filters except tagging them on and I got all of the turned on

<details>

<img width="477" height="855" alt="Image" src="https://github.com/user-attachments/assets/d4cb216d-abd8-443f-8fdd-61483ed47128" />

</details>

**Comment by stephenhawk8054** [comment]
You need to wait for next uBOL version, or add this as your custom filter in the meantime:

```adb
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=poczta.wp.pl|poczta.o2.pl
```

1. Go to uBOL dashboard `Settings` pane 
2. Enable `Developer mode` 
3. Go to `Develop` pane 
4. Choose `Custom DNR rules`
5. Copy paste the above filter(s) and `Save`, open new tab and test again

**Comment by OloTka** [comment]
That worked, thank you !!!

**Comment by krystian3w** [comment]
You also need to remember that this is an unfriendly webmaster and they may want uAssets' work to go to waste.

Then you need to consider unblocking POP3 or IMAP (incoming mails) and SMTP (sending mails) in account settings (all can be in disabled mode) to use:
- own [Roundcube](https://roundcube.net/ "https://roundcube.net/") web client from modern browser 
- app at the level of the operating system of a PC, laptop, tablet or smartphone

**Comment by ktpolanski** [comment]
Seems they rolled out something new, I was previously able to circumvent their adblock nagging by doing a hard refresh in the browser. Less than an hour ago it stopped working, the site didn't respect having the filter turned off uBOL-side, adding the custom filter from the issue also did nothing.

Let me know if I can provide anything to help with this.

**Comment by krystian3w** [comment]
I see new prompt at WP from my private fallback account but not on O2 (legacy account from school time and another used for Facebook):

https://github.com/user-attachments/assets/a6d2a38c-6689-480b-913f-9b03eb058b87

However, this modal may refer to the repair of a supposed lack of vertical scrolling a 2 months ago, which was done ineptly: https://github.com/MajkiIT/polish-ads-filter/pull/23015 these selector is now bad `:not(.overflow-x_hidden, .overflow_hidden, .truncate_true, svg:not(:root), img)` and no worth is write new selectors in not.

It may be necessary to increase the amount of login data (credentials) to their mailbox management system (when created to tests only O2 credentials fails due logins form IP addresses near Romania/USA without a Polish VPN (or too popular cheap/free VPN) can excluded from the ad blocking mechanism).
