### ISSUE TITLE
chip.de: ads

### ISSUE THREAD

**Issue by iknowit-111** [uBlockOrigin/uAssets#30571]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/30157), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://www.github.com/uBlockOrigin/uAssets/discussions/27472) report. _These sites MUST be reported by clicking their **respective links**_.
- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [x] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional or non-default filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [x] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [x] I have turned off all other extensions and the issue still persists. (exception "[Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers)").
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [x] I have verified that the browser I am using is up to date with no pending updates.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://www.chip.de/downloads/Kalmuri-Bildschirm-aufnehmen_182953633.html
```

### Description

go to chip.de ->
downloads ->
try any Program/App

Ads on top and right hand side.

Unable to use picker with right click then left click on the Picker.

### Browser name and version

FF 144 64 bit, 

### Other extensions used

nope

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Image](https://github.com/user-attachments/assets/3e39d99e-88f7-4411-8aae-f038e9a9b393)

![Image](https://github.com/user-attachments/assets/46d230e6-2c73-48c7-954e-4870ad147896)

</details>

### Configuration

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.66.5b2
Firefox: 144
filterset (summary):
 network: 318313
 cosmetic: 261917
 scriptlet: 57547
 html: 2750
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts: 58971-161, 4d.3h.35m
  https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/Steven-Blacks-Porn.txt: 85859-7980, 4d.3h.35m
  adguard-generic: 88218-5335, 2d.18h.12m
  adguard-social: 24941-44, 2d.18h.13m
  adguard-cookies: 35691-78, 2d.18h.12m
  ublock-cookies-adguard: 5215-78, 5d.21h.22m
  adguard-popup-overlays: 28674-893, 2d.18h.13m
  adguard-mobile-app-banners: 6404-95, 2d.18h.13m
  adguard-other-annoyances: 15098-309, 2d.18h.13m
  adguard-widgets: 2969-21, 2d.18h.13m
  fanboy-thirdparty_social: 69-3, 3d.21h.58m
  easylist-annoyances: 5209-467, 5d.21h.21m
  [8 lists not shown]: [too many]
 default:
  user-filters: 13-0, never
  ublock-filters: 41554-71, 3h.8m Δ
  ublock-badware: 10637-31, 3h.8m Δ
  ublock-privacy: 3526-7, 3h.8m Δ
  ublock-unbreak: 2753-14, 3h.8m Δ
  ublock-quick-fixes: 372-12, 3h.8m Δ
  easylist: 83226-148, 3h.8m Δ
  easyprivacy: 54716-803, 3h.8m Δ
  urlhaus-1: 20415-6, 5h.20m
  plowe-0: 3445-2608, 8d.23h.7m
  DEU-0: 8134-44, 22h
filterset (user): [array of 13 redacted]
trustedset:
 added: [array of 31 redacted]
 removed:
  moz-extension-scheme
switchRuleset:
 added: [array of 3 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 trustedListPrefixes: ublock- user-
supportStats:
 allReadyAfter: 531 ms (selfie)
 maxAssetCacheWait: 210 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 18
 network:
  github.com: 18

```
</details>

**Comment by stephenhawk8054** [comment]
@gorhill Are they blocking the iframes, hence the picker can't work?

**Comment by freezer2022** [comment]
> picker

There are several heavy obfuscated inline scripts on the page, one of them breaks the picker, not sure whether intentionally or accidentally, as it's obfuscated, therefore it's purpose is unclear, for the same reason it's unknown whether removing the script will cause any breakages on the site or not.

Anyway removing the script fixes the picker on the page (and removes one of the ads by the way), for example, this is just an example filter, for demonstration, and it works only in Firefox, (one might try to use other text payload or even other kind of uBO filters if possible (maybe some scriplets) ):
```ad
chip.de##^script:has-text(/while \([a-zA-Z]+ > 100\) \{/)
```

**Comment by JobcenterTycoon** [comment]
`www.chip.de##.wrapper-safe:has(> .Downloads-Alternative):remove()` breaks the "Alternative Downloads" section at the bottom.

Its a known issue and they try to mask their ads as legit elements.

**Comment by gorhill** [comment]
> Are they blocking the iframes

The site has (obfuscated) mutation observer code to remove the injected picker iframe.

**Comment by iknowit-111** [comment]
https://www.chip.de/download/

they are doing it again. This time they messed up all download sections.

@JobcenterTycoon 

Can anyone help?

**Comment by JobcenterTycoon** [comment]
Fixed.

**Comment by iknowit-111** [comment]
@JobcenterTycoon  
i cleared cache, reloaded filter lists, but it looks still the same.

Here some Screenshots.

<details>

<img width="1920" height="1040" alt="Image" src="https://github.com/user-attachments/assets/b8c24094-76d1-4579-b46b-103325ef0336" />
<img width="1920" height="1040" alt="Image" src="https://github.com/user-attachments/assets/8129e056-31a9-4f49-a473-dae085a44766" />

</details>

the Opera ad and the Ghostery one

Also the download sections look shabby, like they WANTED to mess it up.

**Comment by JobcenterTycoon** [comment]
The filterlists need a few hours to update.

**Comment by iknowit-111** [comment]
Thank you!
