### ISSUE TITLE
derstandard.at: detection

### ISSUE THREAD

**Issue by AdBlockerFan** [uBlockOrigin/uAssets#30778]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/30157), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://www.github.com/uBlockOrigin/uAssets/discussions/27472) report. _These sites MUST be reported by clicking their **respective links**_.
- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [x] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional or non-default filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [x] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [x] I have turned off all other extensions and the issue still persists. (exception "[Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers)").
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [x] I have verified that the browser I am using is up to date with no pending updates.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL(s) where the issue occurs.

```yaml
https://derstandard.at
```

### Description

DerStandard.at is one of Austria's largest daily newspapers. Since this evening, after opening a news article, users are redirected to a page that checks if an ad blocker is enabled or disabled. uBlock Origin is detected. If uBlock Origin is disabled, the news article opens.

### Browser name and version

Firefox 145.0 (64bit) on Windows 11 25H2

### Other extensions used

none (tried disabling/uninstalling all of the others)

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="607" height="710" alt="Image" src="https://github.com/user-attachments/assets/ca64c1ea-dbf0-4f59-bf58-cf197ed6f74f" />

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.67.0
Firefox: 145
filterset (summary):
 network: 164442
 cosmetic: 47854
 scriptlet: 24033
 html: 2536
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 41902-71, 2h.26m Δ
  ublock-badware: 10555-31, 2h.26m Δ
  ublock-privacy: 3543-2, 2h.26m Δ
  ublock-unbreak: 2765-1, 2h.26m Δ
  ublock-quick-fixes: 387-20, 2h.26m Δ
  easylist: 84928-153, 2h.26m Δ
  easyprivacy: 54806-44, 2h.26m Δ
  urlhaus-1: 29825-5, 11h.9m
  plowe-0: 3468-960, 3d.6h.9m
  DEU-0: 8143-32, 23h.38m
filterset (user): [empty]
userSettings:
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 77 ms (selfie)
 maxAssetCacheWait: 38 ms
 cacheBackend: indexedDB
```
</details>

**Comment by christian-k-at** [comment]
similar issues have been closed with the reason that paywall related issues won't be fixed.

Actually derStandard has no paywall. All articles can be read free of charge with ads.
As on many other pages an ad-free subscription is available - again - this is not a paywall.


A further issue is that uBOL is not always recognized / blocked for some reason. As described in the titel but also this cannot always be reproduced.  Maybe only specific articles trigger this protection.
Might be a way to make it harder to adapt ad-blockers.

Here a link to the ad-block detection 
https://www.derstandard.at/adblockwall/story/3000000296090/die-freie-welt-rocken-und-retten-florian-scheubas-solo-schoenen-guten-abend?ref=seite1_entdecken

When passed forwarded to
https://www.derstandard.at/story/3000000296090/die-freie-welt-rocken-und-retten-florian-scheubas-solo-schoenen-guten-abend


In my case latest chrome on latest Windows 11 fully patched.

**Comment by Hausmarke** [comment]
I can confirm the problem for my computer ar home - stunningly on my computer@work the website works in the same environment as home without any problems...

And to the stuff christian-k-at wrote - when you want access to the site without adds you have to pay - there is no  ad-free subscription... sorry...

**Comment by christian-k-at** [comment]
> when you want access to the site without adds you have to pay 

Thats the/my definition of a subscription that you pay for to access the site without ads --> ad-free subscription

**Comment by Hausmarke** [comment]
Ok - in that case Addblocker do not make sense - i can more or less pay any service to get access without annoying adds...

**Comment by AdBlockerFan** [comment]
I'm impressed with how quickly that was resolved. Thank you very much!

**Comment by AdBlockerFan** [comment]
Sadly they've detected uBlock origin again...

**Comment by oe3gwu** [comment]
Why does a new issue I created [#30835](https://github.com/uBlockOrigin/uAssets/issues/30835) gets closed as duplicate for something that is also closed? I dont get it. This issue still happens and there is currently no open issue for it.

**Comment by stephenhawk8054** [comment]
Why did you tick on this?

> - [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.

**Comment in the old issue threads even when they are closed or even if you have a different problem.**
--

**Comment by uBlock-user** [comment]
> I dont get it.

Why do you care about the issue being open or not ? That is not your prerogative . Just report back here and someone from the team will respond.

**Comment by oe3gwu** [comment]
> Why did you tick on this?
> 
> > * [x]  I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
> 
> ## **Comment in the old issue threads even when they are closed or even if you have a different problem.**

There are 25000 closed issues. So if I take this by word, I wouldnt be allowed to create a new issued even if there was one solved 3 years ago. And even if there was a different problem! This makes no sense technically because closed issues are closed and not worked on. At least this usually is the way.

**Comment by stephenhawk8054** [comment]
When you report, we told you to click on a button to see the issue threads of the same site. Why didn't you click on that?

![share_4597072794162889408.png](https://github.com/user-attachments/assets/a2795627-d0a2-440e-b9d1-32060c98d2ae)

All volunteers are notified with new comments. No need to open another duplicated thread. When we tell you to comment in the old issue thread, just comment in the old issue thread.

**Comment by christian-k-at** [comment]
Sorry if I get something wrong but this issue her is closed. 
Unfortunately it was not solved so the issue was raised again:
https://github.com/uBlockOrigin/uAssets/issues/30835

But the new issue is closed because it is a duplicate of this (already closed) issue.


Does that mean the issue is solved and the users don't use the latest version?
Or should the status of this issue be changed to "re-opened"? 

Question: which issue is the currently active (with the right status) to solve the problem that seems to still persist?

**Comment by stephenhawk8054** [comment]
Just comment in the old issue thread. 

> All volunteers are notified with new comments. No need to open another duplicated thread.

When any volunteer has time to check the issue, it will be investigated and if it needs to be re-opened, they will re-open.

**Comment by christian-k-at** [comment]
I just tested the latest version of uBOL and I can hardly reproduce the issue.

If I directly call the adblock detection site it will recognize also the latest version 2025.1116.1841 which needs to be installed manually as the version available in the store is still 2025.1110.1551.

But navigating randomly on derstandard.at with the new version I don't have detection issues - with the version from the store I do.

So maybe it's just that some users expect the latest version to be available in store?

**Comment by puchu** [comment]
it works on desktop firefox but it doesnt work on android firefox, why?

It seems to work after a manual consent at the page https://www.derstandard.at/consent/tcf/, to get a working version of the page (ad blocker gets detected), one has to disable ublock
