### ISSUE TITLE
[nsfw] mym-db.com: nuisance

### ISSUE THREAD

**Issue by x-R0b0T-x** [uBlockOrigin/uAssets#30935]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/30158), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://www.github.com/uBlockOrigin/uAssets/discussions/27472) report. _These sites MUST be reported by clicking their **respective links**_.
- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [x] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/d22aca5f-58db-4ab3-9b31-8e65a7aeff2e), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional or non-default filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I have disabled the `Developer mode` in uBO Lite's settings and the issue still persists.
- [x] I have verified that the issue still exists after using the [`Optimal` or `Complete` filtering mode](https://user-images.githubusercontent.com/585534/195342612-85d109d9-9006-4eb5-95a5-fec8a4f233ea.png).
- [x] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [x] I have turned off all other extensions and the issue still persists.
- [x] If this is about a breakage or detection, I have verified that it is caused by uBO Lite and isn't a site or browser issue.
- [x] I have verified that the browser I am using is up to date with no pending updates.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://mym-db.com/`

### Category

nuisance

### Description

There are adverts and fake thumbnails.

### Browser name and version

Comet Browser v141.0.7390.55

### Other extensions used

Aucune qui interfère avec uBlock Origin Lite

### Country

France

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

<img width="742" height="117" alt="Image" src="https://github.com/user-attachments/assets/3395d80c-9851-4ea0-be12-abaa2a1fdb83" />

<img width="308" height="343" alt="Image" src="https://github.com/user-attachments/assets/242ad09a-29cf-4499-83e0-e2abebf3605e" />

</details>

### Configuration

```yaml
name: uBlock Origin Lite
version: 2025.1123.1640
browser: Chrome 141 (win)
filtering:
 site: complete
 default: complete
permission: all
rulesets:
 +adguard-mobile
 +adguard-spyware-url
 +annoyances-cookies
 +block-lan
 +rus-0
 +rus-1
 -ublock-badware
 -urlhaus-full
 easylist
 easyprivacy
 fra-0
 pgl
 ublock-filters
```

**Comment by gorhill** [comment]
Seems to work:

    mym-db.com##[data-ad-site]

Should be fixed in regional list.

**Comment by stephenhawk8054** [comment]
```adb
||tech.powergothgirls.com/repo/xyz.js
mym-db.com###swup > .row > div:has(> .card > div[data-ad-site])
```

@smed79 Sorry, can you check this?

**Comment by x-R0b0T-x** [comment]
Hello, the problem persists. All default lists are enabled and my version of UBOL is up to date.

**Comment by gorhill** [comment]
> UBOL is up to date

The newer version is still pending review in Chrome Web Store after a week of releasing 2025.1130.1739. Maybe try with Edge, 2025.1130.1739 is available in Microsoft store -- it updated to latest version same day I published it.

**Comment by x-R0b0T-x** [comment]
Okay, thank you, that makes more sense. For now, I've added this filter:

<img width="662" height="207" alt="Image" src="https://github.com/user-attachments/assets/e22952e2-4efb-4ffe-b43d-7710587cbbc2">

By the way, am I the only one who has aesthetic concerns?
Many websites display empty inserts with a single small pixel in the centre.
