### ISSUE TITLE
Adblock Blocker at mtb-news.de

### ISSUE THREAD

**Issue by demlak** [uBlockOrigin/uAssets#3364]
### URL(s) where the issue occurs
`mtb-news.de`

### Describe the issue
similar to this discription: https://github.com/gorhill/uBlock/issues/1100
if ublock is active, it blocks "ad_pics" in the url "`https://overlays.mtb-news.de/cache/news/feature/ad_pics/...`" and after that, new ad-images are loaded. if ublock is not enabled (therefore does not block "ad_pics", those images are not loaded in here.. 
there are two images.. one at the head and one at the right site which show up after side loaded.. maybe around 5 seconds later.
subdomains (see menu at site top) like bikemarkt, photos, forums, etc.. do have same behaviour.

### Screenshot(s)
![mtb-news](https://user-images.githubusercontent.com/11285006/44818364-1dc54f80-abe9-11e8-95f7-8d89305c45cc.jpg)

### Versions
- Browser/version: [different browsers and versions]
- uBlock Origin version: [v1.16.20]

### Settings
- as far as i remember: default settings

### Notes
as far as my research is correct, this is an addefense-thingy

those things seem to be random:
-filename
-path
-div class
Also size-description in filename and file extensions are wrong/random
Imagesize differs also on different subdomains for the horizontal image on the head

some pictures in the same folder `https://overlays.mtb-news.de/cache/news/feature` are wanted.. for example on this subpage `https://www.mtb-news.de/news/category/magazin/medien/fotostories/`

i'm not a good tester on this, because i don't have access to a complete virgin block-free system. the local network is also filtered on router-stage.

**Comment by okiehsch** [comment]
Already fixed, update your `uBO-filter` list.

**Comment by demlak** [comment]
maybe the other issue is fixed.. but this one in here is new.. it came up the first time today.

**Comment by okiehsch** [comment]
I know and it was fixed today. https://github.com/uBlockOrigin/uAssets/commit/db448baf9a7d23a4695f4e72f635e44a681a9f27

**Comment by okiehsch** [comment]
All addefend sites needed a new fix today, so if you just update your `uBO-filter` list your issue should be fixed.
It is on my end.

**Comment by demlak** [comment]
hmm.. ok.. filter is up to date now.. and filterlist lists issue 3166.
but it still happens in here.. those two images are still ppopping in 5 seconds after site-load.

used ff with private tab (so no cache).. but well. still some adblocking at router

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/44819526-6c74e880-abed-11e8-9c53-635b3a873ab8.png)

`mtb-news.de` with uBO-default setup and up to date filters, using Firefox with a private tab.

If I disable `uBO-filters` and reload the site.
![image](https://user-images.githubusercontent.com/16838044/44819629-d8575100-abed-11e8-804e-aa52dd589be3.png)

**Comment by demlak** [comment]
i don't know, what i should tell you more. it does not filter in here.

**Comment by okiehsch** [comment]
Well, I don't know what to tell you it works here as you can see adn you are not the first one today who complained about addefend issues, for example https://github.com/uBlockOrigin/uAssets/issues/3358

Is mtb-news.de the only site you see this ads or can you reproduce on other websites too?
Go to `welt.de` for example.

**Comment by demlak** [comment]
yes.. welt.de also have same problem in here

**Comment by okiehsch** [comment]
Can you post your logger output of `mtb-news.de`?

- Open the [logger](https://github.com/gorhill/uBlock/wiki/The-logger)

- Load `mtb-news.de`

- Type `dom || ++` in the "filter log entries" box

**Comment by okiehsch** [comment]
Well, your filters are not up to date, your logger shows the filter `uabinject-defuser` which has been completely removed today.

I can't tell you why your system does not update correctly.
https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#update-now
If you click "purge all caches" and then "update now" there should be no `uabinject-defuser` hit in your logger.

**Comment by okiehsch** [comment]
If you can't update your lists, for whatever reason, you can add
`mtb-news.de##script:inject(abort-on-property-read.js, uabpd3)`
to your filter list as a workaround.

**Comment by demlak** [comment]
ok.. so the issue seems to be not updating the uBO-Filters.. i cleared cache and reloaded all filters (like i did several times today).. after that i compared installed filterlist with the one at github here.. they are different.. 

seems i have to find out why there is a difference.. some caching problems.. adon problems.. firefox problems.. i don't know... =(

**Comment by Snuupy** [comment]
The reason @demlak is seeing this is because EasyList contains the rule `/ad_pics/`. I suspect the filter list may also be out of date, but I saw the same issue and I manually forced an update and that did not fix it (maybe it's a bit wonky).

If anything in that directory is blocked, [Ad Defend](https://www.addefend.com/en/) will run and inject more ads in the page (which somehow bypasses uBO)

I believe `uabinject-defuser.js` is a red herring, @okiehsch 

The way that website works is as follows:

If no adblocker, serve regular ads
If adblocker, run Ad Defend script

For example, if I block this image from being loaded (may be different every time I load the page, I'm not sure)
https://overlays.mtb-news.de/cache/news/feature/ad_pics/clair-accelerator_750x401/www.mtb-news.de/news/wp-content/uploads/7GP22018/08/knobs-749x400.png

I will see the injected Ad Defend ads.

It is counterintuitive, but **whitelisting**  the website actually **removes** all the ads. Add this to your "My Filters" tab: 
`@@||mtb-news.de`

When this rule is there, 3rd party trackers (assuming privacy list is still enabled) will still be blocked, regular ads are still blocked, AND ad defend is not triggered, leading to a page with no ads at all :)

I don't know if there is a better way of applying this rule so it is less broad, but this seems to work for me. Am definitely open to suggestions.

With exception rule:
![image](https://user-images.githubusercontent.com/964538/44821779-39f6cb80-abac-11e8-894a-b888d0944142.png)

Without exception rule, I see the ads.

**Comment by okiehsch** [comment]
With an up to date filter list it does not matter if you block `ad_pics` or not
`mtb-news.de##script:inject(abort-on-property-read.js, uabpd3)`
disables the inline-script that triggers the ad-reinsertion.

![image](https://user-images.githubusercontent.com/16838044/44822054-16a63d80-abf9-11e8-979e-9b6514618159.png)

**Comment by okiehsch** [comment]
By the way
`@@||mtb-news.de`
does not whitelist the website, it only allows all requests originating from `mtb-news.de`, so third-party requests will still be blocked if a matching filter exists.

**Comment by okiehsch** [comment]
@demlak 
if you remove `@@||mtb-news.de` from  "My filters" and add 
`mtb-news.de##script:inject(abort-on-property-read.js, uabpd3)` instead you still see ads?

**Comment by demlak** [comment]
I tested both filters. both do work seperaley.

i still got problems here for updating. but this seems to be a deeper firefox and/or filesystem problem.
(the date of extension-data/ublock0.sqlite was from 2017 and after uninstalling uBO, stopping firefox, deleting this file, restarting firefox, installing uBO, the dashboard is broken, can't get into filters, etc..)

i think, this issue can be closed..

**Comment by okiehsch** [comment]
No problem.
Gute Nacht :)

**Comment by okiehsch** [comment]
@demlak having Private Browsing mode enabled can cause your issue, so you could try if disabling it fixes it for you.
Related issues: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1313401
https://github.com/uBlockOrigin/uBlock-issues/issues/195

**Comment by demlak** [comment]
my complete ff profile was problematic.. so i decided to backup the important things and starting a new profile.. uBO updates do work on a fresh install, but not anymore after installing all my plugins..s o i have to find out which one is the problematic one..

BUT: i figured out, that downloading is working (addon debugging).. just updating the filterlists, which are included on first install, does not work. i tried to disable ALL plugins beside uBO. but it still has problems on updating. and also when it works on a fresh ff-profile, the update reveals old filter lists, when it gets problems later with other plugins installed.
so there seems something problematic with storing the filter-lists.

at the moment i don't have too much time to investigate into this.

maybe it is because of using ff 56 here.

**Comment by mapx-** [comment]
Well, FF 56 is full of bugs, use the latest FF.

**Comment by okiehsch** [comment]
https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#read-carefully-if-using-ubowebext
