### ISSUE TITLE
porndig.com[NSFW] [ads] [anti-adblock]

### ISSUE THREAD

**Issue by gidgudmate** [uBlockOrigin/uAssets#3768]
### URL(s) where the issue occurs

`[porndig.com]`

### Describe the issue

[After clicking a video the site will display a blank screen cant see any site contents it only returns to normal if you disable adblock. Video players also have hads on them after pausing the video. Probably more to this site but this is all I found.]

### Versions

- Browser/version: [70.0.3538.67]
- uBlock Origin version: [1.17.0]

### Settings

- [Default]

**Comment by mapx-** [comment]
I addressed the ads, otherwise the video is running fine for me.
Did you test keeping only the default setup ? (and no other blocking extension ? )

**Comment by gidgudmate** [comment]
I have Ublock Origins + Ublock Origin Extra + Nano. The blank screen still appears I was able to hide it with generichide. If I look at the html for the page the class name being used is "noadblock". But yeah generichide seems to work for it.

**Comment by mapx-** [comment]
What if you use only uBo ?

**Comment by gidgudmate** [comment]
Just ubo it shows up. It's very strange cause in the Adblock Warning Removal List a dom filter should be hiding it but it's not. I can only seem to hide it with generichide.

**Comment by mapx-** [comment]
@jspenguin2017

**Comment by gidgudmate** [comment]
So if i disable adblock warning removal list the blank screen disappears. Guessing that's causing more issues then it's helping?

**Comment by mapx-** [comment]
yeah, it's not in the normal setup, it's completely useless.

**Comment by jspenguin2017** [comment]
OK, I'll test it this afternoon.

**Comment by jspenguin2017** [comment]
> it's completely useless.

2 years ago it helps a bit, but yea, these days it's kind of useless...

**Comment by jspenguin2017** [comment]
Fixed.
