### ISSUE TITLE
megawypas.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#4524]
`http://megawypas.com` - blocked right click:

```html
<body bgcolor="#202734" text="#D7DCE9" oncontextmenu="return false">
```

annoyance fix: `megawypas.com##+js(remove-attr.js, oncontextmenu)`

---

https://github.com/MajkiIT/polish-ads-filter/issues/10948 - anti-adblock works in progress

**Comment by okiehsch** [comment]
`megawypas.com##+js(abort-on-property-read.js, qew.init)`
should fix the  anti-adblock message.

**Comment by mapx-** [comment]
or
`megawypas.com##+js(setTimeout-defuser.js, box, 100)`

**Comment by mapx-** [comment]
but .. I remember MajkiIT does not fix anymore anti adb stuff ?!

**Comment by mapx-** [comment]
or simply:
`megawypas.com###qew-notice`

**Comment by krystian3w** [comment]
> but .. I remember MajkiIT does not fix anymore anti adb stuff ?!

Yes, but said to report in her repository.

> https://www.certyficate.it/polskie-filtry-anti-adblock-brak-wsparcia-w-polskich-filtrach-szanowni-nasi-drodzy-od-07-12-2018-nastapia-zmiany-w-oficjalnych-polskich-filtrach/
> > Jedynie o co możemy Was prosić to, nadal zamieszczanie w naszym [repo](https://github.com/MajkiIT/polish-ads-filter/issues) informacji o stronach gdzie wyświetlany jest alert o Adblocku, lecz nie my będziemy to wspierać.

**Comment by okiehsch** [comment]
https://github.com/olegwukr/polish-privacy-filters/issues is now the list that fixes ant-adb messages, but if I recall you can open issues about such messages at the old place.

**Comment by mapx-** [comment]
ok ... well, just closing here
