### ISSUE TITLE
theintercept.com modal popup

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#5281]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://theintercept.com/2019/04/01/lyft-ipo-gig-economy-labor-law/`

### Describe the issue
Modal newsletter subscribe popup on page load

### Screenshot(s)
![theintercept](https://user-images.githubusercontent.com/22258847/55488759-a6ccbb00-55fe-11e9-9a34-027065dac3bb.png)

### Versions

- Browser/version: Chrome Version 74.0.3729.40 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin 1.18.17b0 (Latest Dev Build)
- uBlock Origin Extra 2.80

### Settings

- Test profile with default settings and lists.

**Comment by Mennaruuk** [comment]
Unfortunately, this is back.

**Comment by okiehsch** [comment]
I don't see any modal popup on my end.

**Comment by yourduskquibbles** [comment]
I see it with stock filter lists + uBO Annoyances. I will add `theintercept.com###third-party--viewport-takeover` to UBO Annoyances list.

**Comment by ghost** [comment]
Thank you! Do you know if this would block the popups about joining the newsletter? They show up once I scroll down [this page](https://theintercept.com/drone-papers/firing-blind/).
https://user-images.githubusercontent.com/52135169/130086390-ef20d93c-7f70-4a06-a83c-1c205fae5ce8.png

**Comment by uBlock-user** [comment]
@yourduskquibbles not needed anymore, user can subscribe to Fanboy Annoyances list, both annoyances are fixed there.

**Comment by uBlock-user** [comment]
@ryanbr https://github.com/uBlockOrigin/uAssets/issues/5281#issuecomment-901962208

**Comment by Mennaruuk** [comment]
Unfortunately, I still see the newsletter one even with Fanboy Annoyances enabled.

**Comment by uBlock-user** [comment]
I don't see it on the link you posted, I do see it at `https://theintercept.com/2021/08/18/civil-disorder-prosecutions-racial-justice-protests-extremism/`

`||prod.theintercept.com/checkout/$frame` works.

**Comment by ghost** [comment]
Sorry to bother you even more about this, but the article only loads fully for a couple seconds before it cuts short.

`https://user-images.githubusercontent.com/52135169/130091982-72a82ed4-5f0c-40fd-8f0a-7e9eceb3d49f.mp4`

**Comment by uBlock-user** [comment]
Can't repro that, I see the entire article.

**Comment by yourduskquibbles** [comment]
I can repro, need to add both of following:

`||prod.theintercept.com^$subdocument,1p`
AND 
`theintercept.com##.Post-body--truncated:style(max-height: unset !important;)`

I will add these to Annoyances list since it uses extended syntax.

**Comment by Stillman7896** [comment]
I'm seeing the modal. Can be bypassed by disabling JavaScript

https://github.com/user-attachments/assets/3e84629f-824e-44bf-86cb-48acb004ccdb

https://theintercept.com/2024/07/16/signal-app-privacy-phone-number/

uBlock Origin: 1.68.0
Firefox Mobile: 146
filterset (summary):
 network: 167873
 cosmetic: 123103
 scriptlet: 37075
 html: 3121
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 44952-151, never
  ublock-cookies-easylist: 5136-49, never
  fanboy-social: 17243-15, never
  easylist-annoyances: 4993-145, never
  easylist-chat: 255-0, never
  easylist-newsletters: 8908-25, never
  easylist-notifications: 2434-86, never
  ublock-annoyances: 4636-43, never
 default:
  user-filters: 0-0, never
  ublock-filters: 42984-71, 1m
  ublock-badware: 11390-32, 1m
  ublock-privacy: 3546-2, never
  ublock-unbreak: 2776-1, 1m
  ublock-quick-fixes: 392-14, 1m
  adguard-mobile: 11763-65, 2m
  easylist: 86560-179, 1m
  easyprivacy: 55042-38, 2m
  urlhaus-1: 26795-6, 2m
  plowe-0: 3486-1062, 2m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 4316 ms
 maxAssetCacheWait: 42 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  googletagmanager.com: 1
  parsely.com: 2
  wp.com: 2
 extended:
  ##.share__button
  ##.newsletter-shortcode
  ###share-menu
  ###share-menu-top-button
  ###share-menu-button
  ###third-party--viewport-takeover
  ##a[href^="https://twitter.com/intent/tweet?"]
  ##a[href^="https://www.facebook.com/sharer/sharer.php"]
  ##a[href^="https://www.linkedin.com/shareArticle?"]
  ##.text-\[18px\]:has-text(Support Us)
  ##[data-ga-track-action]:has-text(Join The Conversation)
