### ISSUE TITLE
dailythanthi.com [Anti-Adblock]

### ISSUE THREAD

**Issue by tillcash** [uBlockOrigin/uAssets#7050]
### URL(s) where the issue occurs

```
https://www.dailythanthi.com/
https://www.dailythanthi.com/adblock
```

### Describe the issue

Anti-adblock.

### Screenshot(s)

https://i.imgur.com/B3XnRq4.png

### Versions

- Browser/version: Firefox 68.5.0esr (64-bit)
- uBlock Origin version: 1.25.0

**Comment by okiehsch** [comment]
Same, it is already fixed in `uBO-filters`. If I override that filter I can reproduce.

**Comment by tillcash** [comment]
Updated the filter lists still facing the same issues. Could you provide the filter command so that I can add it manually?

**Comment by tillcash** [comment]
> Same, it is already fixed in `uBO-filters`. If I override that filter I can reproduce.

Updated the filter lists still facing the same issues. Could you provide the filter command so that I can add it manually?

**Comment by okiehsch** [comment]
`@@||dailythanthi.com^$ghide`
works on my end using Chromium or Firefox.
