### ISSUE TITLE
Kissmanga infinite loading if ublock is on

### ISSUE THREAD

**Issue by mparmpuni** [uBlockOrigin/uAssets#7067]
### URL(s) where the issue occurs

`kissmanga.com`

### Describe the issue

The page will "check for browser" forever unless ublock origin is disabled. 

### Screenshot(s)

https://i.imgur.com/SWAwngp.jpg

### Versions

- Browser/version: Chrome/Version 80.0.3987.132 (Official Build) (64-bit)
- uBlock Origin version: 1.24.4

### Settings

- Block All Popups, Disable Cosmetic Filtering

### Notes

If I disable javascript, it tells me to turn it on. If I disable ublock origin, load the page, turn on again, reload page, it lets me continue.

**Comment by uBlock-user** [comment]
@AdamWr need to remove the bab-defuser rule from Adguard Base.

**Comment by mparmpuni** [comment]
I only use easylist filters. should I turn on adguard base too?

**Comment by okiehsch** [comment]
You do not have the built-in filter lists enabled?
![image](https://user-images.githubusercontent.com/16838044/76136684-a883d780-6034-11ea-9860-2a90dd7400f3.png)

**Comment by AdamWr** [comment]
>@AdamWr need to remove the bab-defuser rule from Adguard Base.

Fixed, thank you.

**Comment by mparmpuni** [comment]
Do I need to do anything particular to be able to use the site? I updated the filters lists, added adguard base too, cleared cookies, still not able to access the site with ublock on

**Comment by mapx-** [comment]
go into options / dashboard, purge all caches, update, test again

**Comment by mparmpuni** [comment]
Purging caches seems to have made it work for now. Thank you
