### ISSUE TITLE
fonts.google.com blocked because of incorrect (garbled?) list entry

### ISSUE THREAD

**Issue by grmblgrmbl** [uBlockOrigin/uAssets#7236]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Loading of a Google font from fonts.google.com is prevented. According to the log the following rule is applied:

`||gstaticadssl.l.google.com^$3p`

However, there is no such rule in the rule lists. The closest is

`||gstaticadssl.l.google.com^$~font,third-party,~xmlhttprequest`

from EasyList.

After some time (conditions are not clear) the correct second rule is applied, and loading of the font is permitted.

It looks to me that the first rule is a garbled version of the correct rule.

### A specific URL where the issue occurs

`https://atlas.arages.de`

### Steps to Reproduce

1. Load `https://atlas.arages.de` (uses font Arial instead of Source Sans Pro; check uBlock log)
2. Reload page a few times, wait (conditions are unclear)
3. Font loading is permitted, and correct font is used.

### Expected behavior:

uBlock should apply the correct rule 

`||gstaticadssl.l.google.com^$~font,third-party,~xmlhttprequest`

and permit font loading from the start.

### Actual behavior:

Incorrect rule is applied, and font loading is prevented.

### Your environment

* uBlock Origin version: v1.26.0
* Browser Name and version: FF 75.0
* Operating System and version: Windows 10

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/79226640-ffb06f80-7e5e-11ea-9e15-be8cca475068.png)

**Comment by uBlock-user** [comment]
Yes, it's a CNAME, thought this was fixed twice before.

**Comment by gorhill** [comment]
> After some time (conditions are not clear) the correct second rule is applied

Looks to me as if your EasyList was the one shipped in the package and eventually it updated in the background and you finally ended up with the latest EasyList.

If the issue persists after you first installed uBO and allowed for lists to update, you need to investigate that uBO is able to save the downloaded lists locally.

**Comment by grmblgrmbl** [comment]
If I restart FF everything is OK, and EasyList has the correct entry.
However, if the computer was off over night, and I start FF for the first time in the morning, the problem is back.

This whole thing started about a week ago.

Where does uBlock store the lists?

**Comment by gorhill** [comment]
> Where does uBlock store the lists?

uBO uses a [browser API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local), the browser decides how data is persisted -- uBO does not have access to the file system, just the API. Sometimes a broken profile can prevent the browser API from working properly.

Since you say that restarting Firefox after a long time is causing the local version of lists to be gone, while restarting Firefox after a short while is not causing this, maybe you need to investigate if something else on your system is causing your Firefox profile to be messed with overnight.

**Comment by grmblgrmbl** [comment]
I've now removed uBlock, restarted FF, re-installed uBlock, and updated all filter lists. FF apparently has created a new local storage for the lists, and the problem has not re-appeared so far.
