### ISSUE TITLE
www.joysound.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7320]
### URL(s) where the issue occurs

`https://www.joysound.com/web/search/song/746956`

### Describe the issue

Annoyances: context menu, copy, and text-selection disabled

### Screenshot(s)

![joysound1](https://user-images.githubusercontent.com/58900598/81244929-a4812f80-904e-11ea-99af-5301b9446c2d.png)

### Versions

- Browser/version: 1.8.90
- uBlock Origin version: 1.26.0

### Settings

- Default + uBlock Annoyances

### Notes

As style overriding didn't work, I added
```
joysound.com##+js(set, document.body.oncopy, null)
joysound.com##+js(set, document.body.onselectstart, null)
joysound.com##+js(set, document.body.oncontextmenu, null)
```
as set by `https://www.joysound.com/web/feature/search/js/songdetail.min.js`, then the page hid the lyrics:

![joysound2](https://user-images.githubusercontent.com/58900598/81245034-f7f37d80-904e-11ea-9334-981845c7fc37.png)

**Comment by uBlock-user** [comment]
`set` sets the value in **early** which is causing site breakage(`document.body` gets set to `null` as per dev-tools). You will need an event based setter/getter scriptlet or do it manually by copy-pasting in the console after page-load --

`document.body.oncontextmenu = document.body.onselectstart = document.body.oncopy = null;`

**Comment by mapx-** [comment]
@gorhill

**Comment by gorhill** [comment]
I could prevent the context menu from being disable with:

    joysound.com##+js(aopr, document.body.oncontextmenu)

However, the same approach did not work for the selection.

The reason is how the `aopr` scriptlet is written and I think this can be overcome with the same fix I did [here](https://github.com/gorhill/uBlock/commit/034c915f3be1257ed5de638a456e7c95932c553d#diff-d7616deaf3a39e3f19f8d70d098bfe7a).

**Comment by uBlock-user** [comment]
> joysound.com##+js(aopr, document.body.oncontextmenu)

doesn't it break anything ?

**Comment by mapx-** [comment]
`joysound.com##+js(aopr, document.body.oncontextmenu)` does not work either, it breaks the "pretender" section (see the pic above)

**Comment by gorhill** [comment]
Oh I see, I need to investigate more then -- though it wouldn't hurt to ensure that `set` and `aopr` are reentrant-resistant.

**Comment by gorhill** [comment]
Ok, `document.body` is special, though the scriptlet traps the property to detect when its value changes, the browser is modifying its value internally, bypassing the trap.

**Comment by uBlock-user** [comment]
https://github.com/NanoAdblocker/NanoFilters/blob/master/NanoFiltersSource/NanoResources.txt#L27 will work for this case.

**Comment by gorhill** [comment]
Right... This kind of lead me back to the idea of simple operators which can be chained, in such case it would be to merely add a `match-readystate` operator and thus all scriptlet operators which would follow would be executed after the target ready state is reached, without keeping duplicating code.

    +js:match-readystate(/interactive|complete/):set-constant(document.body.oncontextmenu, null)

**Comment by uBlock-user** [comment]
That would be much better ofcourse and without having to resort to adding another scriptlet, also you can shorten `match-readystate` to just `:readystate` as we don't have any such existing operator.

**Comment by kulfoon** [comment]
It seems gorhill likes to keep words match/watch as a first part of the name (matches-css, matches-css-before, matches-css-after, watch-attr) for procedural operators (but I think that will apply to scriplets as well), so I'm curious, following this logic:  [`:watch-attributes`](https://github.com/uBlockOrigin/uBlock-issues/issues/341#issuecomment-449854596) ==> [`:watch-attrs`](https://github.com/uBlockOrigin/uBlock-issues/issues/341#issuecomment-449860631) ==> [`:watch-attr`](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectwatch-attrsarg) 
we get____________________________________`:match-readystate` ==> ---------------- ==> `:match-rdy`

**Comment by AndnixSH** [comment]
In this case, I'm using Enable Right Click extension and works perfectly
but it had been removed from Chrome webstore

**Comment by Yuki2718** [comment]
I guess found another case.
[NSFW] `https://www.j-live.tv/`

**Comment by jdet123** [comment]
Use a separate extension. Search chrome web store with "enable right click", "enable copy", etc, there are many extensions that removes copy restrictions.

I recommend the one named "Ultimate Enable Right Click". It automatically removes copy restriction without needing to click on the extension icon.

uBlock origin can only apply fix for websites added in filters, but a separate extension can fix any websites.

**Comment by Yuki2718** [comment]
@jdet123 
There's simply no such magic, have you ever read the source code of the extension? Your recommended extension doesn't work on the website in question (only unblock right click). The extension you recommended unconditionally injects JS and user stylesheet to every websites, which is possible by uBO too - we don't do this for performance and also for potential problem. In fact the extension has internal whitelist. Most websites don't need them. Anyway it's off-topic.

**Comment by jdet123** [comment]
> Your recommended extension doesn't work on the website in question (only unblock right click)

You haven't activated the CSS thingy on this website

> The extension you recommended unconditionally injects JS and user stylesheet to every websites,

uBlock scriptlets aopr or aopw are much more dangerous. Maybe you are under a religious belief that "unconditional" injection is bad.. In this regards, uBlock "unconditionally" injects content scripts to every websites too. To me, what is more important is whether that code does what it's supposed to do. Also I haven't seen any performance issues, so I recommend.

**Comment by mapx-** [comment]
`document.body.oncopy`
https://github.com/uBlockOrigin/uAssets/issues/12528

**Comment by mapx-** [comment]
This issue should be fixed with the [last improvement of `set-constant` scriptlet](https://github.com/gorhill/uBlock/commit/e1500ee88d2524da0c93e85b8855d0671a3c6cdb)

```
Add ability to defer set-constant execution
A new optional parameter has been added to `set-constant`
scriptlet: `runAt`, default to `0`.

 ..##+js(set, document.body.oncontextmenu, null, 2)

When the `runAt` parameter is present, uBO will take it into
account to possibly defer execution of `set-constant`:

- `runAt` not present: execute immediately
- `runAt` = 1: execute immediately
- `runAt` = 2: execute when document state is "interactive"
- `runAt` = 3: execute when document state is `"complete"
```

Tested in firefox, `uBO 1.48.9b1`

(sometimes I need more than 1 refresh)

```
joysound.com##+js(set, document.body.oncopy, null, 3)
joysound.com##+js(set, document.body.onselectstart, null, 3)
joysound.com##+js(set, document.body.oncontextmenu, null, 3)
joysound.com##body:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
joysound.com##style:has-text(@media print):remove()
```

**Comment by gorhill** [comment]
> This issue should be fixed with the [last improvement of set-constant scriptlet](https://github.com/gorhill/uBlock/commit/e1500ee88d2524da0c93e85b8855d0671a3c6cdb)

I used the case here to test but it didn't fix it on my side (at least in Chromium). There is this weird state in the DOM where `document.body.oncontextmenu` is `null`, but the event listener that was assigned to it is still executed by the browser.

**Comment by mapx-** [comment]
maybe it's why even in firefox the right-click is still disabled but upon refreshing the page it will finally work

**Comment by mapx-** [comment]
@gorhill 

adding this filter makes right click works in chrome on my end

`joysound.com##+js(aeld, DOMContentLoaded, ready)`

**Comment by gorhill** [comment]
Nice, so the extra parameter was indeed required to solve this issue.

**Comment by gorhill** [comment]
@Yuki2718 Are you satisified that the following filters (using dev build) are taking care of the issue?

    joysound.com##+js(set, document.body.oncopy, null, 3)
    joysound.com##+js(set, document.body.onselectstart, null, 3)
    joysound.com##+js(set, document.body.oncontextmenu, null, 3)
    joysound.com##+js(aeld, DOMContentLoaded, ready)
    joysound.com##body:style(user-select: unset !important)

**Comment by Yuki2718** [comment]
Yes, they're working fine, thx!

**Comment by gorhill** [comment]
I am going to change the last parameter to make the purpose more clear, and I to align the value with already existing documentation out there. So it will be:

    `end` or `interactive`: at `DOMContentLoaded` event time
    `idle` or `complete`: at `load` event time

Anything else will be "as soon as possible".

**Comment by stephenhawk8054** [comment]
So for future filters that need `runAt` parameter, we will need to write in JSON format, is it correct?

**Comment by gorhill** [comment]
Depends of the scriptlet. For `set-constant`, the positional form is available; for `aeld`, only with the JSON notation.

**Comment by stephenhawk8054** [comment]
Got it
