### ISSUE TITLE
Fox News Videos Do Not Play Under Firefox Using uBlock Origin

### ISSUE THREAD

**Issue by Clepsy** [uBlockOrigin/uAssets#7485]
### Description

Videos on Fox News do not run on Firefox when uBlock Origin is enabled.  Even after several minutes, the spinning graphic indicates they're loading, but they never run.  In Google Chrome, using uBlock Origin, they run just fine.

### A specific URL where the issue occurs

`https://www.foxnews.com/politics/sen-cruz-calls-for-criminal-investigation-into-twitter-for-violating-us-sanctions-on-iran`

### Steps to Reproduce

1. Install the latest version of Windows 10 on an Intel machine.
2. Install the latest version of Firefox
3. Install the latest version of uBlock Origin on Firefox
4. Load the specific URL
5. Click the Play triangle

### Expected behavior:

I expect the video to play.

### Actual behavior:

The video does not play.

### Your environment

* uBlock Origin version:  v1.27.10
* Browser Name and version:  Mozilla Firefox 76.0.1 (64-bit)
* Operating System and version:  Windows 10 Version 1909 (OS Build 18363.836)

**Comment by uBlock-user** [comment]
![captured](https://user-images.githubusercontent.com/21290713/83344850-f190b280-a329-11ea-8c04-919a39c3fc30.png)

Working as expected.

**Comment by Yuki2718** [comment]
I can reproduce the issue but even without uBO. Turning Firefox's Tracking Protection off solved it.

**Comment by adranger** [comment]
@englehardt please check this report.

**Comment by lain566** [comment]
Fixed.

**Comment by Clepsy** [comment]
Still not playing.

    On Sunday, May 31, 2020, 05:54:47 PM MDT, lain566 <notifications@github.com> wrote:  
 
 


Closed #7485 via 8845b5a.

**Comment by lain566** [comment]
I can reproduce your issue if Firefox Tracking Protection is enabled, if after updating your filter lists it still doesn't work, then something might be wrong on your side.

**Comment by Clepsy** [comment]
Ah, thank you for your response.

As I value security above any single source of news, I suppose I'll just be watching other sources until/unless Fox News gets their act together.  

I sent them a polite plug for Firefox, along with a request they restore compatibility.  :)

 - Steve
    On Sunday, May 31, 2020, 11:15:05 PM MDT, lain566 <notifications@github.com> wrote:  
 
 


I can reproduce your issue if Firefox Tracking Protection is enabled, if after updating your filter lists it still doesn't work, then something might be wrong on your side.

**Comment by THEtomaso** [comment]
> https://github.com/uBlockOrigin/uAssets/commit/8845b5a0c683766a3a81d42841a2d494265b872a

This rule breaks video playback for Pale Moon and SeaMonkey (possibly other non-Chromium browsers too):
`||c.amazon-adsystem.com/aax2/apstag.js$script,domain=foxnews.com,important`

Examples:
`https://video.foxnews.com/`

Could someone test with other browsers (e.g. Firefox)?
At the very least, this `$badfilter` fix should be added to uBO's Legacy filter:
`||c.amazon-adsystem.com/aax2/apstag.js$script,domain=foxnews.com,important,badfilter`

**Comment by lain566** [comment]
I can't reproduce any breakage in playback  with Firefox and Chromium.


> At the very least, this `$badfilter` fix should be added to uBO's Legacy filter:
> `||c.amazon-adsystem.com/aax2/apstag.js$script,domain=foxnews.com,important,badfilter`
> (PS: This doesn't seem to trigger any ads)

That filter has no effect on my side.

**Comment by Yuki2718** [comment]
Is the resource-redirect working on the legacy browsers?

**Comment by mapx-** [comment]
No issue on my end in waterfox

**Comment by THEtomaso** [comment]
Thanks for testing, guys.
I've found the problem now..
The rule that I mentied in my previous post DOES break video playback for the browsers that I mentioned.
..but, ONLY if this script is whitelisted (which is was in one of my other filters):
`https://imasdk.googleapis.com/js/sdkloader/ima3.js`
Usually, video breakage is caused by blocking that script, so this is a rare opposite case! :)
