### ISSUE TITLE
mediumarticles.com{ Antiadblock }

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7574]
### URL(s) where the issue occurs

`https://mediumarticles.com/CJIt`

### Describe the issue
Antiadblock 

### Screenshot(s)

`https://prnt.sc/t2828a`

### Versions

- Browser/version: firefox 
- uBlock Origin version: 1.27.10

### Settings

 uBO's default settings

**Comment by dumbusernameidk** [comment]
popups to junk sites and sometimes when clicking on the bottom half of the page it opens a new tab showing a logo

`https://exey.io/39AIBSC`

**Comment by dumbusernameidk** [comment]
exey.io has anti-adblock link above should still work.

**Comment by dumbusernameidk** [comment]
'exey.io' has anti-adblock. link above still works.

**Comment by mapx-** [comment]
it was fixed today. update your filters

**Comment by dumbusernameidk** [comment]
just updated and issue still persists. tried clearing cache and cookies as well.

**Comment by mapx-** [comment]
Do you see this filter in the logger ?
https://github.com/uBlockOrigin/uAssets/commit/746155dde5deae7b1d8a539dd8bfb0f97ac3103e

**Comment by dumbusernameidk** [comment]
yes.

**Comment by mapx-** [comment]
tested again FF / chrome all fine here

**Comment by dumbusernameidk** [comment]
tried both still wont work. also i don't know if it's related but the console says the page2ad script fails to load because of `ERR_CONNECTION_REFUSED`.

**Comment by mapx-** [comment]
maybe something else in your system is blocking it

**Comment by dumbusernameidk** [comment]
i completely whitelisted the page even and it still refuses. must be a site issue or something with google.

**Comment by PerfectSalad** [comment]
> i completely whitelisted the page even and it still refuses. must be a site issue or something with google.

Do you have a built-in-the-browser ad / tracker blocker? @dumbusernameidk

**Comment by PerfectSalad** [comment]
> i completely whitelisted the page even and it still refuses. must be a site issue or something with google.

Do you have a built-in-the-browser ad / tracker blocker?

**Comment by dumbusernameidk** [comment]
just ublock and tampermonkey but i have no scripts running for any google site.

**Comment by PerfectSalad** [comment]
Any hosts file?

**Comment by dumbusernameidk** [comment]
yes that was it. forgot i blocked some google services because of spotify.

**Comment by dumbusernameidk** [comment]
another one to whitelist unless it got fixed already `@@||pagead2.googlesyndication.com/pagead/managed/js/adsense$script,domain=exey.io`

**Comment by dumbusernameidk** [comment]
@mapx- 
`
exey.io##+js(abort-current-script, JSON.parse, break;case $.)` causing anti-adblock to trigger.

**Comment by mapx-** [comment]
fixed, update in 5-10 min

**Comment by dumbusernameidk** [comment]
`exey.io##+js(aost, Math.random, /\st\.[a-zA-Z]*\s/)` causing breakage.

**Comment by stephenhawk8054** [comment]
> `exey.io##+js(aost, Math.random, /\st\.[a-zA-Z]*\s/)` causing breakage.

It's updated already: [https://github.com/uBlockOrigin/uAssets/commit/29a41ffaad3d2a7ea5f12f52a66596b48e542d80](https://github.com/uBlockOrigin/uAssets/commit/29a41ffaad3d2a7ea5f12f52a66596b48e542d80). Force update your filter lists.

**Comment by dumbusernameidk** [comment]
exey.io has anti-adblock.
