### ISSUE TITLE
removes lenovo contact us chat buttons

### ISSUE THREAD

**Issue by bughit** [uBlockOrigin/uAssets#8144]
### URL(s) where the issue occurs

`https://www.lenovo.com/us/en/contact`

### Describe the issue

the "chat with us" buttons on the above page disappear when ubo is active

### Screenshot(s)

without ubo
![image](https://user-images.githubusercontent.com/895588/98039092-27135d80-1dec-11eb-8e1c-838c88ce20e4.png)

with ubo
![image](https://user-images.githubusercontent.com/895588/98039138-3a262d80-1dec-11eb-89a5-9f8013e65a2f.png)

### Versions

- Browser/version: Chrome 86.0.4240.183, Firefox 82.0.2
- uBlock Origin version: 1.30.6

**Comment by mapx-** [comment]
test

```
@@||static.atgsvcs.com/js/atgsvcs.js$script,domain=lenovo.com
@@||rules.atgsvcs.com/EERules/view/rules/*/json/$xhr,domain=lenovo.com
```

@ryanbr

**Comment by kokotas89** [comment]
working!

**Comment by uBlock-user** [comment]
fixed in EP.

**Comment by bughit** [comment]
@uBlock-user A filter lists update in ubo didn't resolve this. How does this fix get to ubo?

**Comment by uBlock-user** [comment]
The fix was added in EasyPrivacy, did you update that list in particular ?

**Comment by kokotas89** [comment]
Check the compilation date of your easyprivacy list in ubo. It took one day for mine to be updated to the new one on ubo development edition.if you still can't get it add the filters as your own custom filter until the update is pushed to your ubo as well.

**Comment by bughit** [comment]
Filter list update was forced, so EasyPrivacy was updated.
```
[Adblock Plus 1.1]
! Version: 202011050037
! Title: EasyPrivacy
! Last modified: 05 Nov 2020 00:37 UTC
! Expires: 4 days (update frequency)
! Homepage: https://easylist.to/
! Licence: https://easylist.to/pages/licence.html
```
the new entries are there
```
@@||rules.atgsvcs.com/EERules/view/$domain=lenovo.com
@@||static.atgsvcs.com/js/atgsvcs.js$domain=lenovo.com|officedepot.com|shop.lego.com
```
but the "chat with us" buttons are still missing, until ubo is deactivated for the page

**Comment by kokotas89** [comment]
Hmm for me it's working. Have you tried ctrl+F5 to for e a cache refresh?

**Comment by bughit** [comment]
Before, I was refreshing the page and the buttons weren't there but after deactivating and reactivating ubo, they appeared.

**Comment by kokotas89** [comment]
Ah great then !
