### ISSUE TITLE
"videos" don't work on similar sites

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8471]
### URL(s) where the issue occurs

```
https://videos.memedeportes.com/2021/01/un-jugador-marca-un-golazo-al-estilo.html
https://videos.cuantarazon.com/2021/01/un-conejo-queda-atrapado-por-sus-largas.html
https://videos.vistoenlasredes.com/2021/01/un-conejo-queda-atrapado-por-sus-largas.html
https://videos.vrutal.com/2021/01/super-mario-3d-all-stars-explora-el.html
https://videos.humorenserie.com/2020/12/stillwater-la-pelicula-animada-de-apple.html
```

### Describe the issue

I think they are not actually videos from these websites, they are videos of advertisements, trailers etc. For example, in main page of **memedeportes.com** has a widget in the sidebar that redirect to: `https://videos.memedeportes.com/2021/01/un-jugador-marca-un-golazo-al-estilo.html`

### Screenshot(s)

![Captura](https://user-images.githubusercontent.com/33556647/104664906-acf73300-56d0-11eb-8d70-01478e3860f3.PNG)

### Versions

- Browser/version: [GOOGLE CHROME]
- uBlock Origin version: [1.32.4]

### Notes

I don't know if it should be fixed, because it seems like an idea of the adserver: `https://www.ampliffy.com/`

**Comment by bug-rules** [comment]
May need many tests:

```
@@||tpc.googlesyndication.com/pimgad/$image,domain=videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||tpc.googlesyndication.com/pageadimg/imgad$image,domain=videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com


```

**Comment by mapx-** [comment]
well, to get the video (webm) you need lots of exceptions (filters only for `videos.memedeportes.com`):

```
@@||tpc.googlesyndication.com/pageadimg/imgad$image,media,domain=videos.memedeportes.com
@@||tpc.googlesyndication.com/pimgad/$image,media,domain=videos.memedeportes.com
@@||gvt1.com/videoplayback/$media,domain=videos.memedeportes.com
@@*$xhr,domain=videos.memedeportes.com
@@||googletagservices.com^$script,domain=videos.memedeportes.com
@@||imasdk.googleapis.com/js/sdkloader/ima3_debug.js$script,domain=videos.memedeportes.com
@@||tpc.googlesyndication.com^$script,domain=videos.memedeportes.com
@@||doubleclick.net^$script,domain=videos.memedeportes.com
```

**Comment by PIZZA90** [comment]
the videos working with that filters, but with big ZOOM and no controls of videoplayer.

`https://videos.memedeportes.com/2020/12/un-nadador-rompe-el-record-mundial-de.html`

**Comment by uBlock-user** [comment]
Are those even website videos ? or just third-party ad videos ?

**Comment by mapx-** [comment]
I modified to get the controls `@@*$xhr,css,domain=videos.memedeportes.com`

**Comment by PIZZA90** [comment]
I wondered that in the post, im not sure if is ads, or "video-memes" uBlock-user

**Comment by mapx-** [comment]
imo those are legitimate videos

**Comment by uBlock-user** [comment]
legitmate videos hosted on an ad-server ?

**Comment by mapx-** [comment]
yeah, that's strange, but if you watch them .. the videos seem ok (the remaining filters filter out the video ads !)

**Comment by mapx-** [comment]
@PIZZA90 now (after fixing the controls) you could check if the filters above are working for all those pages

**Comment by PIZZA90** [comment]
is working:

```
@@||tpc.googlesyndication.com/pageadimg/imgad$image,media,domain=videos.memedeportes.com|videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||tpc.googlesyndication.com/pimgad/$image,media,domain=videos.memedeportes.com|videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||gvt1.com/videoplayback/$media,domain=videos.memedeportes.com|videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@*$xhr,css,domain=videos.memedeportes.com|videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||googletagservices.com^$script,domain=videos.memedeportes.com|videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||imasdk.googleapis.com/js/sdkloader/ima3_debug.js$script,domain=videos.memedeportes.com|videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||tpc.googlesyndication.com^$script,domain=videos.memedeportes.com|videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||doubleclick.net^$script,domain=videos.memedeportes.com|videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
```

**Comment by mapx-** [comment]
well, now you could try to propose the filters to spa: `EasyList Spanish` or/ and `spa, por: AdGuard Spanish/Portuguese`

**Comment by PIZZA90** [comment]
exist a github of that lists?

**Comment by mapx-** [comment]
@Alex-302 for adguard

and easylist spanish
https://github.com/easylist/easylistspanish/issues

**Comment by PIZZA90** [comment]
thanks, good work!

**Comment by PIZZA90** [comment]
https://github.com/uBlockOrigin/uAssets/issues/8471

**Comment by PIZZA90** [comment]
https://github.com/easylist/easylistspanish/issues/151

**Comment by mapx-** [comment]
@PIZZA90 replace `xhr` by `xmlhttprequest` (easylist does not use uBO abbreviations)

**Comment by PIZZA90** [comment]
true! done

**Comment by mapx-** [comment]
`css` too => `stylesheet`

**Comment by PIZZA90** [comment]
I delete de other comment, the domain `videos.memedeportes.com` was duplicated, I leave it here updated, also in `/easylistspanish`


```
@@||tpc.googlesyndication.com/pageadimg/imgad$image,media,domain=videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||tpc.googlesyndication.com/pimgad/$image,media,domain=videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||gvt1.com/videoplayback/$media,domain=videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@*$xmlhttprequest,stylesheet,domain=videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||googletagservices.com^$script,domain=videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||imasdk.googleapis.com/js/sdkloader/ima3_debug.js$script,domain=videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||tpc.googlesyndication.com^$script,domain=videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
@@||doubleclick.net^$script,domain=videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com
```

was a copy-paste of **bug-rules**  😁😁

**Comment by Yuki2718** [comment]
Still there: `@@*$xhr,css,`

**Comment by PIZZA90** [comment]
well this is uBO repository... in `/easylistspanish` is fixed 😁

**Comment by mapx-** [comment]
@PIZZA90 Alex optimized the filters, maybe you should adapt those for easylist spanish

**Comment by PIZZA90** [comment]
here is adapted for EL spanish 🤔

https://github.com/easylist/easylistspanish/issues/151

**Comment by PIZZA90** [comment]
duplicated domains

https://github.com/AdguardTeam/AdguardFilters/commit/ce5d94b8315a469c039990b05c5da04dc14af140

**Comment by PIZZA90** [comment]
i dont know if is correct now:

https://github.com/easylist/easylistspanish/issues/151

**Comment by mapx-** [comment]
> duplicated domains
> 
> [AdguardTeam/AdguardFilters@ce5d94b](https://github.com/AdguardTeam/AdguardFilters/commit/ce5d94b8315a469c039990b05c5da04dc14af140)

already corrected https://github.com/AdguardTeam/AdguardFilters/commit/56e64c7dfeab692dc42b1f8a313460b86439f47b

**Comment by mapx-** [comment]
> i dont know if is correct now:
> 
> [easylist/easylistspanish#151](https://github.com/easylist/easylistspanish/issues/151)

You have to provide exactly the same filters in adguard

**Comment by PIZZA90** [comment]
if you want.. add also:

`@@||tpc.googlesyndication.com/pimgad/*$image,domain=videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com`

or add the `*` to the filter, for the pictures in main page, (see the picture of the main post)

`https://www.memedeportes.com/`

**Comment by bug-rules** [comment]
but Perter lowe also break this pages?

**Comment by PIZZA90** [comment]
hey friends!! i cant see any of the filters of this posts, working in the logs (is added in: **spa, por: AdGuard Spanish/Portuguese**)

`https://videos.memedeportes.com/2021/03/un-futbolista-anota-un-estratosferico.html`

i dont know what happens here. The filters not doing the work?

**Comment by mapx-** [comment]
add
`@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=videos.memedeportes.com`

**Comment by Alex-302** [comment]
Fixed in our filter

**Comment by PIZZA90** [comment]
hey! :-)

`https://videos.vistoenlasredes.com/2021/05/un-centenar-de-bufalos-cruzan-nado-un.html`

the problem is back xDD a lot things is whitelisted and blocked in the logs, really is a headache this issue.

the problem is in all domains found in this post.

**Comment by mapx-** [comment]
test
`@@*.m3u8$xhr,domain=videos.memedeportes.com|videos.memedeportes.com|videos.cuantarazon.com|videos.vistoenlasredes.com|videos.vrutal.com|videos.humorenserie.com`

@Alex-302
